import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, existsSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";
import vm from "node:vm";
import ts from "typescript";
import { JSDOM } from "jsdom";

test("mode switching preserves independent designs and routes material choices and exports", async () => {
  const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost" });
  const previous = new Map();
  for (const [key, value] of Object.entries({ window: dom.window, document: dom.window.document, navigator: dom.window.navigator, localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true })) {
    previous.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, writable: true, value });
  }
  dom.window.matchMedia = () => ({ matches: false, addEventListener() {}, removeEventListener() {} });
  dom.window.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  dom.window.HTMLDialogElement.prototype.close = function () { this.open = false; };
  const require = createRequire(import.meta.url), React = require("react"), { createRoot } = require("react-dom/client");
  const project = fileURLToPath(new URL("../", import.meta.url)), cache = new Map();
  // Test real controls and shell with only the WebGL renderers stubbed.
  function load(file) {
    if (cache.has(file)) return cache.get(file).exports;
    if (file.endsWith("/preview-stage.tsx")) return { PreviewStage: () => React.createElement("div", null, "Case preview") };
    if (file.endsWith("/protector-preview.tsx")) return { ProtectorPreview: () => React.createElement("div", null, "Protector preview") };
    if (file.endsWith("/stand-preview.tsx")) return { StandPreview: () => React.createElement("div", null, "Stand preview") };
    const mod = { exports: {} }; cache.set(file, mod);
    const code = ts.transpileModule(readFileSync(file, "utf8"), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true } }).outputText;
    const localRequire = specifier => {
      if (!specifier.startsWith(".") && !specifier.startsWith("@/")) return require(specifier);
      const base = specifier.startsWith("@/") ? path.join(project, specifier.slice(2)) : path.resolve(path.dirname(file), specifier);
      const resolved = [base, `${base}.ts`, `${base}.tsx`].find(existsSync);
      return /\.tsx?$/.test(resolved) ? load(resolved) : require(resolved);
    };
    new vm.Script(`(function(require, module, exports) {${code}\n})`, { filename: file }).runInThisContext()(localRequire, mod, mod.exports);
    return mod.exports;
  }
  const downloads = [], blobs = new Map(), originalCreate = URL.createObjectURL, originalRevoke = URL.revokeObjectURL;
  URL.createObjectURL = blob => { const url = `blob:test-${blobs.size}`; blobs.set(url, blob); return url; };
  URL.revokeObjectURL = () => {};
  dom.window.HTMLAnchorElement.prototype.click = function () { downloads.push({ name: this.download, blob: blobs.get(this.href) }); };
  const root = createRoot(document.getElementById("root"));
  const button = label => {
    const match = [...document.querySelectorAll("button")].find(element => element.getAttribute("aria-label") === label || element.textContent.trim() === label);
    assert.ok(match, `button ${label} exists`); return match;
  };
  const click = async label => React.act(async () => { button(label).click(); });
  try {
    const { ConfiguratorShell } = load(path.join(project, "components/configurator-shell.tsx"));
    await React.act(async () => { root.render(React.createElement(ConfiguratorShell)); });
    assert.equal(button("Case designer").getAttribute("aria-pressed"), "true");
    const section = title => [...document.querySelectorAll(".config-section")].find(element => element.querySelector("h3").textContent === title);
    const toggleSection = async title => React.act(async () => { section(title).querySelector("summary").click(); });
    assert.equal(section("Dimensions").open, true);
    assert.equal(section("Accessories").open, false);
    await toggleSection("Accessories");
    await click("Integrated handles");
    assert.equal(section("Accessories").open, true, "Changing a control keeps its section open");
    await toggleSection("Accessories");
    assert.match(section("Accessories").querySelector("summary").textContent, /1 handle/);
    await click("104");
    assert.equal(section("Accessories").open, false, "Unrelated changes preserve collapsed sections");
    assert.match(section("Accessories").querySelector("summary").textContent, /2 handles/);
    await toggleSection("Accessories");
    assert.equal(button("Integrated handles").getAttribute("aria-checked"), "true");
    await click("Integrated handles");
    await toggleSection("Ventilation");
    await click("Bottom ventilation");
    assert.equal(document.querySelector(".vent-options").hidden, true);
    assert.match(section("Ventilation").querySelector("summary").textContent, /Off/);
    await click("Bottom ventilation");
    assert.equal(document.querySelector(".vent-options").hidden, false);
    assert.equal(section("Ventilation").open, true);
    await click("Synth stand");
    assert.equal(button("Synth stand").getAttribute("aria-pressed"), "true");
    assert.ok(document.querySelector('[aria-label="Synth stand controls"]'));
    assert.equal(section("Your instrument").open, true);
    assert.equal(section("Playing angle").open, false);
    await toggleSection("Playing angle");
    assert.equal(button("Front extension").getAttribute("aria-checked"), "false");
    assert.equal(document.querySelector('input[aria-label="Extension length in mm"]'), null);
    await click("Front extension");
    assert.equal(document.querySelector('input[aria-label="Extension length in mm"]').value, "15");
    assert.equal(section("Playing angle").open, true);
    await toggleSection("Playing angle");
    assert.match(section("Playing angle").querySelector("summary").textContent, /15 mm front extension/);
    await toggleSection("Material & fit");
    assert.equal(button("Rounded edges").getAttribute("aria-checked"), "false");
    await click("Rounded edges");
    assert.ok(document.querySelector('input[aria-label="Corner radius in mm"]'));
    assert.equal(section("Playing angle").open, false, "Other stand edits preserve collapsed sections");
    assert.match(section("Material & fit").querySelector("summary").textContent, /Rounded edges/);
    await toggleSection("Cable management");
    assert.equal(button("Cable holes in braces").getAttribute("aria-checked"), "false");
    await click("Cable holes in braces");
    assert.equal(button("Cable holes in braces").getAttribute("aria-checked"), "true");
    assert.ok(document.querySelector('input[aria-label="Cable hole diameter in mm"]'));
    await toggleSection("Playing angle");
    assert.equal(button("Front extension").getAttribute("aria-checked"), "true");
    await click("35°");
    await click("Material library");
    await React.act(async () => document.querySelector('dialog button[aria-label="Blue"]').click());
    const selectValue = async (select, value) => React.act(async () => {
      select.value = value;
      select.dispatchEvent(new dom.window.Event("change", { bubbles: true }));
    });
    await selectValue(document.querySelector("dialog select"), "opal");
    await click("Close notes");
    await click("Export JSON");
    const stand = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(stand.mode, "synth-stand"); assert.equal(stand.configuration.angle, 35); assert.equal(stand.configuration.tint.id, "blue");
    assert.equal(stand.configuration.transparency, "opal");
    assert.equal(stand.configuration.cableHoles, true);
    assert.equal(stand.configuration.roundedEdges, true);
    assert.equal(stand.configuration.frontExtension, true);
    assert.equal(stand.frontExtension.length, 15);
    assert.equal(stand.edgeRounding.requestedRadius, 3);
    assert.equal(stand.cableManagement.totalCount, (stand.construction.ribCount - 1) * 3);
    assert.match(section("Playing angle").querySelector("summary").textContent, /35° tilt/);
    assert.match(section("Material & fit").querySelector("summary").textContent, /Blue/);
    assert.ok(section("Cable management").querySelector("summary").textContent.includes(`${stand.cableManagement.totalCount} holes`));
    assert.ok(section("Your parts").querySelector("summary").textContent.includes(`${stand.construction.totalParts} parts`));
    await click("Cutting layout");
    assert.equal(document.querySelector('svg[aria-label^="Cutting layout:"]').querySelectorAll("path").length, stand.construction.totalParts);
    const bracePath = [...document.querySelectorAll('svg[aria-label^="Cutting layout:"] g')].find(group => group.textContent.includes("Front cross brace")).querySelector("path");
    assert.equal((bracePath.getAttribute("d").match(/\bM/g) ?? []).length, stand.cableManagement.countPerBrace + 1);
    await click("Export stand sheets as SVG");
    assert.match(downloads.at(-1).name, /stand.*sheets\.svg$/);
    assert.match(await downloads.at(-1).blob.text(), /35 degrees/);
    await click("Synth protector");
    assert.equal(button("Synth protector").getAttribute("aria-pressed"), "true");
    assert.ok(document.querySelector('[aria-label="Synth protector controls"]'));
    await click("50 mm");
    await click("Material library");
    await React.act(async () => document.querySelector('dialog button[aria-label="Red"]').click());
    await selectValue(document.querySelector("dialog select"), "see-through");
    await click("Close notes");
    await click("Export JSON");
    const protector = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(protector.mode, "synth-protector");
    assert.equal(protector.configuration.headroom, 50);
    assert.equal(protector.configuration.tint.id, "red");
    assert.equal(protector.configuration.transparency, "see-through");
    assert.equal(protector.parts.length, 5);
    await click("Cutting layout");
    assert.equal(document.querySelector('svg[aria-label^="Cutting layout:"]').querySelectorAll("path").length, 5);
    await click("Export protector sheets as SVG");
    assert.match(downloads.at(-1).name, /protector.*sheets\.svg$/);
    assert.match(await downloads.at(-1).blob.text(), /Body-to-cover clearance 50 mm/);
    await click("Build notes");
    assert.match(document.querySelector("dialog").textContent, /A little room above the controls/);
    await click("Close notes");
    await click("Synth stand");
    await click("Export JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).configuration.tint.id, "blue");
    await click("Synth protector");
    assert.equal(button("50 mm").getAttribute("aria-pressed"), "true");
    await click("Case designer");
    assert.equal(button("104").getAttribute("aria-pressed"), "true");
    await click("Export JSON");
    const caseData = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(caseData.configuration.hp, 104); assert.equal(caseData.configuration.tint.id, "orange");
    assert.equal(caseData.configuration.transparency, "transparent");
    await toggleSection("Material");
    assert.equal(document.querySelectorAll('[aria-label="Acrylic color"] button').length, 11);
    await click("Use individual acrylic materials for each sheet");
    await selectValue(document.querySelector("#panel-tint-front"), "black");
    const transparencySelect = label => {
      const field = [...document.querySelectorAll("label")].find(element => element.textContent === label);
      assert.ok(field, `field ${label} exists`);
      return document.getElementById(field.htmlFor);
    };
    await selectValue(transparencySelect("Front transparency"), "opaque");
    await click("Export JSON");
    let materialCase = JSON.parse(await downloads.at(-1).blob.text()).configuration;
    assert.equal(materialCase.panelTints.front.id, "black");
    assert.equal(materialCase.panelTransparencies.front, "opaque");
    assert.equal(materialCase.panelTransparencies.bottom, "transparent");
    await click("Red");
    await click("Export JSON");
    materialCase = JSON.parse(await downloads.at(-1).blob.text()).configuration;
    assert.ok(Object.values(materialCase.panelTints).every(tint => tint.id === "red"));
    assert.equal(materialCase.panelTransparencies.front, "opaque", "Applying color preserves sheet finishes");
    await selectValue(document.querySelector("#panel-tint-left"), "white");
    await selectValue(transparencySelect("All sheets’ transparency"), "see-through");
    await click("Export JSON");
    materialCase = JSON.parse(await downloads.at(-1).blob.text()).configuration;
    assert.ok(Object.values(materialCase.panelTransparencies).every(value => value === "see-through"));
    assert.equal(materialCase.panelTints.left.id, "white", "Applying transparency preserves sheet colors");
    await click("Use individual acrylic materials for each sheet");
    await click("Use individual acrylic materials for each sheet");
    assert.equal(document.querySelector("#panel-tint-left").value, "white", "Toggling individual mode retains choices");
    // Exercise the real row controls through both exports, including row edits.
    const addRow = async units => React.act(async () => {
      [...document.querySelectorAll(".rack-add button")].find(element => element.textContent.trim() === `${units}U`).click();
    });
    const setRowAngle = async (row, value) => React.act(async () => {
      const label = [...document.querySelectorAll("label")].find(element => element.textContent === `Row ${row} extra angle`);
      const input = document.getElementById(label.htmlFor);
      Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(input, String(value));
      input.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
    });
    await addRow(3);
    await setRowAngle(1, 35);
    await addRow(1);
    await setRowAngle(2, 20);
    await click("Export JSON");
    let angledCase = JSON.parse(await downloads.at(-1).blob.text());
    assert.deepEqual(angledCase.configuration.rowAngles, [35, 20, 0]);
    assert.deepEqual(angledCase.rowLayout.rows.map(row => row.angle), [55, 20, 0]);
    assert.equal(angledCase.rowLayout.automaticFeet, true);
    await click("30°");
    await click("Export JSON");
    angledCase = JSON.parse(await downloads.at(-1).blob.text());
    assert.deepEqual(angledCase.configuration.rowAngles, [25, 20, 0]);
    await click("Move row 1 toward front");
    await click("Remove row 1");
    await click("Export JSON");
    angledCase = JSON.parse(await downloads.at(-1).blob.text());
    assert.deepEqual(angledCase.configuration.rowAngles, [25, 0]);
    await click("Export all sheets as SVG");
    assert.equal(((await downloads.at(-1).blob.text()).match(/data-part=/g) ?? []).length, 5);
    await click("Remove row 1");
    assert.equal(document.querySelector('[aria-label="Additional row angles"]'), null);

    await click("Synth stand");
    assert.equal(button("35°").getAttribute("aria-pressed"), "true");
    assert.equal(button("Front extension").getAttribute("aria-checked"), "true");
    await click("Front extension");
    assert.equal(document.querySelector('input[aria-label="Extension length in mm"]'), null);
    await click("Export JSON");
    const compactStand = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(compactStand.configuration.transparency, "opal", "Case edits preserve stand finish");
    assert.equal(compactStand.frontExtension.length, 0);
    assert.equal(compactStand.configuration.frontExtensionLength, 15);
    assert.equal(button("Rounded edges").getAttribute("aria-checked"), "true");
    await click("Rounded edges");
    assert.equal(document.querySelector('input[aria-label="Corner radius in mm"]'), null);
    assert.equal(button("Cable holes in braces").getAttribute("aria-checked"), "true");
    await click("Cable holes in braces");
    assert.equal(document.querySelector('input[aria-label="Cable hole diameter in mm"]'), null);
    await click("Build notes");
    assert.match(document.querySelector("dialog").textContent, /Slot together\. Play at your angle/);
    assert.match(document.querySelector("dialog").textContent, /no load capacity or stability rating/);
  } finally {
    await React.act(async () => root.unmount());
    URL.createObjectURL = originalCreate; URL.revokeObjectURL = originalRevoke;
    for (const [key, descriptor] of previous) { if (descriptor) Object.defineProperty(globalThis, key, descriptor); else delete globalThis[key]; }
    dom.window.close();
  }
});
