import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync, existsSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";
import vm from "node:vm";
import ts from "typescript";
import { JSDOM } from "jsdom";
import { IDBFactory } from "fake-indexeddb";

test("mode switching preserves independent designs and routes material choices and exports", async () => {
  const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost" });
  const previous = new Map();
  for (const [key, value] of Object.entries({ indexedDB: new IDBFactory(), Element: dom.window.Element, window: dom.window, document: dom.window.document, navigator: dom.window.navigator, localStorage: dom.window.localStorage, DOMParser: dom.window.DOMParser, XMLSerializer: dom.window.XMLSerializer, SVGSVGElement: dom.window.SVGSVGElement, IS_REACT_ACT_ENVIRONMENT: true })) {
    previous.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { configurable: true, writable: true, value });
  }
  dom.window.matchMedia = () => ({ matches: false, addEventListener() {}, removeEventListener() {} });
  dom.window.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  dom.window.HTMLDialogElement.prototype.close = function () { this.open = false; };
  const require = createRequire(import.meta.url), React = require("react"), { createRoot } = require("react-dom/client");
  const project = fileURLToPath(new URL("../", import.meta.url)), cache = new Map();
  // Test real controls and shell with only the WebGL renderers stubbed.
  function load(file) {
    if (cache.has(file)) return cache.get(file).exports;
    if (file.endsWith("/speaker-preview.tsx")) return { SpeakerPreview: () => React.createElement("div", null, "Speaker preview") };
    if (file.endsWith("/art-preview.tsx")) return { ArtPreview: () => React.createElement("div", null, "Art preview") };
    if (file.endsWith("/panel-preview.tsx")) return { PanelPreview: () => React.createElement("div", null, "Panel preview") };
    if (file.endsWith("/case-preview.tsx")) return { CasePreview: () => React.createElement("div", null, "Case preview") };
    if (file.endsWith("/protector-preview.tsx")) return { ProtectorPreview: () => React.createElement("div", null, "Protector preview") };
    if (file.endsWith("/stand-preview.tsx")) return { StandPreview: () => React.createElement("div", null, "Stand preview") };
    const mod = { exports: {} }; cache.set(file, mod);
    const code = ts.transpileModule(readFileSync(file, "utf8").replaceAll("import.meta.url", JSON.stringify(pathToFileURL(file).href)), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true } }).outputText;
    const localRequire = specifier => {
      if (!specifier.startsWith(".") && !specifier.startsWith("@/")) return require(specifier);
      const base = specifier.startsWith("@/") ? path.join(project, specifier.slice(2)) : path.resolve(path.dirname(file), specifier);
      const resolved = [base, `${base}.ts`, `${base}.tsx`].find(existsSync);
      return /\.tsx?$/.test(resolved) ? load(resolved) : require(resolved);
    };
    new vm.Script(`(function(require, module, exports) {${code}\n})`, { filename: file }).runInThisContext()(localRequire, mod, mod.exports);
    return mod.exports;
  }
  const downloads = [], blobs = new Map(), originalCreate = URL.createObjectURL, originalRevoke = URL.revokeObjectURL;
  URL.createObjectURL = blob => { const url = `blob:test-${blobs.size}`; blobs.set(url, blob); return url; };
  URL.revokeObjectURL = () => {};
  dom.window.HTMLAnchorElement.prototype.click = function () { downloads.push({ name: this.download, blob: blobs.get(this.href) }); };
  const root = createRoot(document.getElementById("root"));
  const button = label => {
    const match = [...document.querySelectorAll("button")].find(element => element.getAttribute("aria-label") === label || element.textContent.trim() === label);
    assert.ok(match, `button ${label} exists`); return match;
  };
  const click = async label => React.act(async () => {
    const target = button(label), menu = target.closest(".project-menu");
    if (menu && !menu.open) menu.querySelector("summary").click();
    target.click();
  });
  try {
    const { ConfiguratorShell } = load(path.join(project, "components/configurator-shell.tsx"));
    await React.act(async () => { root.render(React.createElement(ConfiguratorShell)); });
    assert.equal(button("Case designer").getAttribute("aria-pressed"), "true");
    assert.equal(document.querySelector(".workspace .fabrication-workspace"), null, "Fabrication no longer extends the main workspace");
    for (const [modeLabel, firstPart] of [["Speaker case", "Driver baffle"], ["Case designer", "Bottom"], ["Synth stand", "Support rib 1"], ["Synth protector", "Protective top sheet"], ["Panel designer", "Panel"], ["Art mode", "Sheet A-1"]]) {
      await click(modeLabel);
      const trigger = button("Fabrication workspace");
      assert.ok(trigger.closest(".summary-panel"), "Each mode opens fabrication from its specification section");
      assert.equal(trigger.getAttribute("aria-haspopup"), "dialog");
      const overlay = document.getElementById(trigger.getAttribute("aria-controls"));
      assert.equal(overlay.open, false);
      await click("Fabrication workspace");
      assert.equal(overlay.open, true);
      assert.match(overlay.querySelector("#fabrication-description").textContent, new RegExp(modeLabel));
      assert.equal(overlay.querySelector("tbody td").textContent, firstPart, "The overlay uses the active mode's parts");
      await React.act(async () => overlay.querySelector("h2").click());
      assert.equal(overlay.open, true, "Clicking content keeps the overlay open");
      await click("Download sheet 1");
      const sheet = new dom.window.DOMParser().parseFromString(await downloads.at(-1).blob.text(), "image/svg+xml");
      assert.ok([...sheet.querySelectorAll("g > title")].some(title => title.textContent === firstPart), "Stock download contains the active design");
      await click("Download fit coupon");
      assert.match(downloads.at(-1).name, /fit-coupon\.svg$/);
      const widthInput = overlay.querySelector(".stock-controls input");
      await React.act(async () => {
        Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(widthInput, "1200");
        widthInput.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
      });
      await click("Close fabrication workspace");
      assert.equal(overlay.open, false);
      await click("Fabrication workspace");
      assert.equal(widthInput.value, "1200", "Stock settings survive closing and reopening");
      assert.match(overlay.querySelector(".stock-sheet svg").getAttribute("viewBox"), /^0 0 1200 /);
      await React.act(async () => overlay.click());
      assert.equal(overlay.open, false, "Clicking the backdrop closes the overlay");
    }
    await click("Speaker case");
    await click("Staggered dots");
    assert.equal(button("Staggered dots").getAttribute("aria-checked"), "false");
    await click("Export speaker design JSON");
    const speakerDesign = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(speakerDesign.mode, "speaker");
    assert.equal(speakerDesign.parts.length, 7);
    assert.equal(speakerDesign.configuration.staggered, false);
    await click("Cutting layout");
    const speakerPaths = [...document.querySelectorAll(".stand-cutting-layout path")].map(p => p.getAttribute("d"));
    await click("Export speaker sheets as SVG");
    const speakerSvg = new dom.window.DOMParser().parseFromString(await downloads.at(-1).blob.text(), "image/svg+xml");
    assert.deepEqual(speakerPaths, [...speakerSvg.querySelectorAll("path")].map(p => p.getAttribute("d")));
    await click("Case designer");
    await click("Speaker case");
    assert.equal(button("Staggered dots").getAttribute("aria-checked"), "false");
    await click("Build notes");
    assert.match(document.querySelector(".info-dialog:not(.project-dialog)").textContent, /passive radiators/);
    await click("Close notes");
    await click("Art mode");
    await click("Cutting layout");
    assert.equal(document.querySelector('svg[aria-label="Art cutting layout: 8 slotted sheets"]').querySelectorAll("g[data-part]").length, 8);
    await click("Leaf shelves");
    assert.equal(button("Leaf shelves").getAttribute("aria-checked"), "true");
    assert.equal(document.querySelectorAll('.stand-cutting-layout g[data-part]').length, 16);
    assert.equal(document.querySelectorAll('#art-sheet option').length, 8, "Growth controls only list main leaves");
    await click("Export art design JSON");
    const shelved = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(shelved.configuration.leafShelves, true);
    assert.equal(shelved.parts.filter(p => p.shelf).length, 8);
    await click("Use individual acrylic materials for each sheet");
    assert.equal(document.querySelector('select[aria-label="Leaf shelf A-1 color"]'), null, "Shelf appearance follows its parent instead of offering a separate color");
    const leafColor = document.querySelector('select[aria-label="Sheet A-1 color"]');
    await React.act(async () => {
      leafColor.value = "blue";
      leafColor.dispatchEvent(new dom.window.Event("change", { bubbles: true }));
    });
    const parentFill = document.querySelector('.stand-cutting-layout [data-part="a-1"] path').getAttribute("fill");
    assert.equal(document.querySelector('.stand-cutting-layout [data-part="shelf-a-1"] path').getAttribute("fill"), parentFill);
    await click("Export art design JSON");
    const colored = JSON.parse(await downloads.at(-1).blob.text()).sheetMaterials;
    assert.equal(colored.find(p => p.id === "shelf-a-1").tint.id, "blue");
    await click("Undo design change");
    await click("Undo design change");
    await click("Undo design change");
    assert.equal(button("Leaf shelves").getAttribute("aria-checked"), "false");
    assert.equal(document.querySelectorAll('.stand-cutting-layout g[data-part]').length, 8);
    await click("New growth pattern");
    await click("Export art design JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).configuration.seed,509);
    await click("Undo design change");
    await click("Export art design JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).configuration.seed,508);
    await click("Redo design change");
    await click("Bend the leaves");
    await click("Export art sheets as SVG");
    assert.doesNotMatch(await downloads.at(-1).blob.text(),/data-operation="bend-guide"/);
    await click("Bend the leaves");
    await click("Material library");
    await React.act(async () => document.querySelector('.info-dialog:not(.project-dialog) button[aria-label="Blue"]').click());
    await click("Close notes");
    await click("Export art design JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).configuration.tint.id,"blue");
    await click("Build notes");
    assert.match(document.querySelector(".info-dialog:not(.project-dialog)").textContent,/acrylic botany/);
    await click("Close notes");
    await click("Case designer");
    await click("Cutting layout");
    assert.equal(button("Cutting layout").getAttribute("aria-pressed"), "true");
    assert.equal(button("Perspective").getAttribute("aria-pressed"), "false");
    const caseLayout = () => document.querySelector('svg[aria-label="Case cutting layout: all five enclosure sheets"]');
    assert.equal(caseLayout().querySelectorAll("path").length, 5);
    const originalBottomPath = caseLayout().querySelector('[data-part="bottom"] path').getAttribute("d");
    await click("Export all sheets as SVG");
    const exportedLayout = new dom.window.DOMParser().parseFromString(await downloads.at(-1).blob.text(), "image/svg+xml");
    for (const part of caseLayout().querySelectorAll("g[data-part]")) {
      assert.equal(part.querySelector("path").getAttribute("d"), exportedLayout.querySelector(`[data-part="${part.dataset.part}"] path`).getAttribute("d"));
    }
    const engravingSection = [...document.querySelectorAll(".config-section")].find(el => el.querySelector("h3").textContent === "Custom engravings");
    await React.act(async () => engravingSection.querySelector("summary").click());
    const engravingInput = engravingSection.querySelector('input[aria-label="Import SVG engraving"]');
    const svgFile = { name: "etched-mark.svg", size: 120, text: async () => '<svg xmlns="http://www.w3.org/2000/svg"><path d="M0 0H20V20H0Z M5 5V15H15V5Z" fill-rule="evenodd" /></svg>' };
    Object.defineProperty(engravingInput, "files", { configurable: true, value: [svgFile] });
    await React.act(async () => engravingInput.dispatchEvent(new dom.window.Event("change", { bubbles: true })));
    assert.equal(engravingSection.querySelectorAll(".cutout-list-row").length, 1);
    assert.ok(caseLayout().querySelector('[data-operation="engrave"]'), "Flat preview displays engravings");
    assert.equal(caseLayout().querySelector('[data-part="bottom"] path').getAttribute("d"), originalBottomPath);
    await click("Duplicate etched-mark");
    assert.equal(engravingSection.querySelectorAll(".cutout-list-row").length, 2);
    await click("Remove etched-mark copy");
    await click("Undo design change");
    assert.equal(engravingSection.querySelectorAll(".cutout-list-row").length, 2);
    await click("Redo design change");
    await click("Remove etched-mark");
    assert.equal(caseLayout().querySelector('[data-operation="engrave"]'), null);
    const frontBeforeLed = caseLayout().querySelector('[data-part="front"] path').getAttribute("d");
    await React.act(async () => engravingSection.querySelector('input[aria-label="LED strip · Front sheet"]').click());
    assert.notEqual(caseLayout().querySelector('[data-part="front"] path').getAttribute("d"), frontBeforeLed);
    await click("Undo design change");
    assert.equal(caseLayout().querySelector('[data-part="front"] path').getAttribute("d"), frontBeforeLed);
    await click("Front");
    assert.equal(caseLayout(), null);
    assert.equal(button("Front").getAttribute("aria-pressed"), "true");
    await click("Cutting layout");
    await click("Exploded view");
    assert.equal(caseLayout(), null);
    assert.equal(button("Exploded view").getAttribute("aria-pressed"), "true");
    await click("Cutting layout");
    assert.equal(button("Exploded view").getAttribute("aria-pressed"), "false");
    await click("Reset camera");
    assert.equal(caseLayout(), null);
    assert.equal(button("Perspective").getAttribute("aria-pressed"), "true");
    await click("Cutting layout");
    const section = title => [...document.querySelectorAll(".config-section")].find(element => element.querySelector("h3").textContent === title);
    const toggleSection = async title => React.act(async () => { section(title).querySelector("summary").click(); });
    assert.equal(section("Dimensions").open, true);
    assert.equal(section("Accessories").open, false);
    await toggleSection("Accessories");
    await click("Integrated handles");
    assert.equal(section("Accessories").open, true, "Changing a control keeps its section open");
    await toggleSection("Accessories");
    assert.match(section("Accessories").querySelector("summary").textContent, /1 handle/);
    await click("104");
    assert.notEqual(caseLayout().querySelector('[data-part="bottom"] path').getAttribute("d"), originalBottomPath, "Cutting layout updates when case dimensions change");
    assert.equal(section("Accessories").open, false, "Unrelated changes preserve collapsed sections");
    assert.match(section("Accessories").querySelector("summary").textContent, /2 handles/);
    await toggleSection("Accessories");
    assert.equal(button("Integrated handles").getAttribute("aria-checked"), "true");
    await click("Integrated handles");
    await toggleSection("Ventilation");
    await click("Bottom ventilation");
    assert.equal(document.querySelector(".vent-options").hidden, true);
    assert.match(section("Ventilation").querySelector("summary").textContent, /Off/);
    await click("Bottom ventilation");
    assert.equal(document.querySelector(".vent-options").hidden, false);
    assert.equal(section("Ventilation").open, true);
    await click("Synth stand");
    assert.equal(button("Synth stand").getAttribute("aria-pressed"), "true");
    assert.ok(document.querySelector('[aria-label="Synth stand controls"]'));
    assert.equal(section("Your instrument").open, true);
    assert.equal(section("Playing angle").open, false);
    await toggleSection("Playing angle");
    assert.equal(button("Front extension").getAttribute("aria-checked"), "false");
    assert.equal(document.querySelector('input[aria-label="Extension length in mm"]'), null);
    await click("Front extension");
    assert.equal(document.querySelector('input[aria-label="Extension length in mm"]').value, "15");
    assert.equal(section("Playing angle").open, true);
    await toggleSection("Playing angle");
    assert.match(section("Playing angle").querySelector("summary").textContent, /15 mm front extension/);
    await toggleSection("Material & fit");
    assert.equal(button("Rounded edges").getAttribute("aria-checked"), "false");
    await click("Rounded edges");
    assert.ok(document.querySelector('input[aria-label="Corner radius in mm"]'));
    assert.equal(section("Playing angle").open, false, "Other stand edits preserve collapsed sections");
    assert.match(section("Material & fit").querySelector("summary").textContent, /Rounded edges/);
    await toggleSection("Cable management");
    assert.equal(button("Cable holes in braces").getAttribute("aria-checked"), "false");
    await click("Cable holes in braces");
    assert.equal(button("Cable holes in braces").getAttribute("aria-checked"), "true");
    assert.ok(document.querySelector('input[aria-label="Cable hole diameter in mm"]'));
    await toggleSection("Playing angle");
    assert.equal(button("Front extension").getAttribute("aria-checked"), "true");
    await click("35°");
    await click("Material library");
    await React.act(async () => document.querySelector('.info-dialog:not(.project-dialog) button[aria-label="Blue"]').click());
    const selectValue = async (select, value) => React.act(async () => {
      select.value = value;
      select.dispatchEvent(new dom.window.Event("change", { bubbles: true }));
    });
    await selectValue(document.querySelector(".info-dialog:not(.project-dialog) select"), "opal");
    await click("Close notes");
    await click("Design JSON");
    const stand = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(stand.mode, "synth-stand"); assert.equal(stand.configuration.angle, 35); assert.equal(stand.configuration.tint.id, "blue");
    assert.equal(stand.configuration.transparency, "opal");
    assert.equal(stand.configuration.cableHoles, true);
    assert.equal(stand.configuration.roundedEdges, true);
    assert.equal(stand.configuration.frontExtension, true);
    assert.equal(stand.frontExtension.length, 15);
    assert.equal(stand.edgeRounding.requestedRadius, 3);
    assert.equal(stand.cableManagement.totalCount, (stand.construction.ribCount - 1) * 3);
    assert.match(section("Playing angle").querySelector("summary").textContent, /35° tilt/);
    assert.match(section("Material & fit").querySelector("summary").textContent, /Blue/);
    assert.ok(section("Cable management").querySelector("summary").textContent.includes(`${stand.cableManagement.totalCount} holes`));
    assert.ok(section("Your parts").querySelector("summary").textContent.includes(`${stand.construction.totalParts} parts`));
    await click("Cutting layout");
    assert.equal(document.querySelector('svg[aria-label^="Cutting layout:"]').querySelectorAll("path").length, stand.construction.totalParts);
    const bracePath = [...document.querySelectorAll('svg[aria-label^="Cutting layout:"] g')].find(group => group.textContent.includes("Front cross brace")).querySelector("path");
    assert.equal((bracePath.getAttribute("d").match(/\bM/g) ?? []).length, stand.cableManagement.countPerBrace + 1);
    await click("Export stand sheets as SVG");
    assert.match(downloads.at(-1).name, /stand.*sheets\.svg$/);
    assert.match(await downloads.at(-1).blob.text(), /35 degrees/);
    await click("Synth protector");
    assert.equal(button("Synth protector").getAttribute("aria-pressed"), "true");
    assert.ok(document.querySelector('[aria-label="Synth protector controls"]'));
    await click("50 mm");
    await click("Material library");
    await React.act(async () => document.querySelector('.info-dialog:not(.project-dialog) button[aria-label="Red"]').click());
    await selectValue(document.querySelector(".info-dialog:not(.project-dialog) select"), "see-through");
    await click("Close notes");
    await click("Design JSON");
    const protector = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(protector.mode, "synth-protector");
    assert.equal(protector.configuration.headroom, 50);
    assert.equal(protector.configuration.tint.id, "red");
    assert.equal(protector.configuration.transparency, "see-through");
    assert.equal(protector.parts.length, 5);
    await click("Cutting layout");
    assert.equal(document.querySelector('svg[aria-label^="Cutting layout:"]').querySelectorAll("path").length, 5);
    await click("Export protector sheets as SVG");
    assert.match(downloads.at(-1).name, /protector.*sheets\.svg$/);
    assert.match(await downloads.at(-1).blob.text(), /Body-to-cover clearance 50 mm/);
    await click("Build notes");
    assert.match(document.querySelector(".info-dialog:not(.project-dialog)").textContent, /A little room above the controls/);
    await click("Close notes");
    await click("Synth stand");
    await click("Design JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).configuration.tint.id, "blue");
    await click("Synth protector");
    assert.equal(button("50 mm").getAttribute("aria-pressed"), "true");
    await toggleSection("Feet & edge fit");
    await click("Feet on all four edges");
    const setProtectorNumber = async (label, value) => React.act(async () => {
      const input = document.querySelector(`input[aria-label="${label}"]`);
      assert.ok(input);
      Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(input, String(value));
      input.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
    });
    await setProtectorNumber("Extra feet per left / right edge in feet", 1);
    await setProtectorNumber("Extra feet per front / rear edge in feet", 3);
    await toggleSection("Locking strips");
    await click("Through-tabs & locking strips");
    await click("Design JSON");
    const retained = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(retained.construction.footCount, 16);
    assert.equal(retained.construction.stripCount, 4);
    assert.equal(retained.parts.length, 21);
    assert.equal(retained.configuration.allSides, true);
    assert.equal(retained.retention.enabled, true);
    await click("Cutting layout");
    assert.equal(document.querySelector('svg[aria-label^="Cutting layout:"]').querySelectorAll("path").length, 21);
    await click("Export protector sheets as SVG");
    assert.match(await downloads.at(-1).blob.text(), /16 feet, 4 retaining strips/);
    await click("Feet on all four edges");
    await click("Design JSON");
    const sideOnly = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(sideOnly.construction.footCount, 6);
    assert.equal(sideOnly.construction.stripCount, 2);
    await click("Through-tabs & locking strips");
    await click("Design JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).construction.stripCount, 0);
    await click("Feet on all four edges");
    assert.equal(document.querySelector('input[aria-label="Extra feet per front / rear edge in feet"]').value, "3");

    await click("Case designer");
    assert.equal(button("104").getAttribute("aria-pressed"), "true");
    await click("Design JSON");
    const caseData = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(caseData.configuration.hp, 104); assert.equal(caseData.configuration.tint.id, "orange");
    assert.equal(caseData.configuration.transparency, "transparent");
    await toggleSection("Material");
    assert.equal(document.querySelectorAll('[aria-label="Acrylic color"] button').length, 11);
    await click("Use individual acrylic materials for each sheet");
    await selectValue(document.querySelector("#panel-tint-front"), "black");
    const transparencySelect = label => {
      const field = [...document.querySelectorAll("label")].find(element => element.textContent === label);
      assert.ok(field, `field ${label} exists`);
      return document.getElementById(field.htmlFor);
    };
    await selectValue(transparencySelect("Front transparency"), "opaque");
    await click("Design JSON");
    let materialCase = JSON.parse(await downloads.at(-1).blob.text()).configuration;
    assert.equal(materialCase.panelTints.front.id, "black");
    assert.equal(materialCase.panelTransparencies.front, "opaque");
    assert.equal(materialCase.panelTransparencies.bottom, "transparent");
    await click("Red");
    await click("Design JSON");
    materialCase = JSON.parse(await downloads.at(-1).blob.text()).configuration;
    assert.ok(Object.values(materialCase.panelTints).every(tint => tint.id === "red"));
    assert.equal(materialCase.panelTransparencies.front, "opaque", "Applying color preserves sheet finishes");
    await selectValue(document.querySelector("#panel-tint-left"), "white");
    await selectValue(transparencySelect("All sheets’ transparency"), "see-through");
    await click("Design JSON");
    materialCase = JSON.parse(await downloads.at(-1).blob.text()).configuration;
    assert.ok(Object.values(materialCase.panelTransparencies).every(value => value === "see-through"));
    assert.equal(materialCase.panelTints.left.id, "white", "Applying transparency preserves sheet colors");
    await click("Use individual acrylic materials for each sheet");
    await click("Use individual acrylic materials for each sheet");
    assert.equal(document.querySelector("#panel-tint-left").value, "white", "Toggling individual mode retains choices");
    // Exercise the real row controls through both exports, including row edits.
    const addRow = async units => React.act(async () => {
      [...document.querySelectorAll(".rack-add button")].find(element => element.textContent.trim() === `${units}U`).click();
    });
    const setRowAngle = async (row, value) => React.act(async () => {
      const label = [...document.querySelectorAll("label")].find(element => element.textContent === `Row ${row} extra angle`);
      const input = document.getElementById(label.htmlFor);
      Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(input, String(value));
      input.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
    });
    await addRow(3);
    await setRowAngle(1, 35);
    await addRow(1);
    await setRowAngle(2, 20);
    await click("Design JSON");
    let angledCase = JSON.parse(await downloads.at(-1).blob.text());
    assert.deepEqual(angledCase.configuration.rowAngles, [35, 20, 0]);
    assert.deepEqual(angledCase.rowLayout.rows.map(row => row.angle), [55, 20, 0]);
    assert.equal(angledCase.rowLayout.automaticFeet, true);
    await click("30°");
    await click("Design JSON");
    angledCase = JSON.parse(await downloads.at(-1).blob.text());
    assert.deepEqual(angledCase.configuration.rowAngles, [25, 20, 0]);
    await click("Move row 1 toward front");
    await click("Remove row 1");
    await click("Design JSON");
    angledCase = JSON.parse(await downloads.at(-1).blob.text());
    assert.deepEqual(angledCase.configuration.rowAngles, [25, 0]);
    await click("Export all sheets as SVG");
    assert.equal(((await downloads.at(-1).blob.text()).match(/data-part=/g) ?? []).length, 5);
    await click("Remove row 1");
    assert.equal(document.querySelector('[aria-label="Additional row angles"]'), null);

    await click("Panel designer");
    assert.equal(button("Panel designer").getAttribute("aria-pressed"), "true");
    assert.ok(document.querySelector('[aria-label="Panel designer controls"]'));
    const field = text => [...document.querySelectorAll("label")].find(label => label.textContent.startsWith(text)).querySelector("input, select");
    const setPanelNumber = async (label, value) => React.act(async () => {
      const input = field(label);
      Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(input, String(value));
      input.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
    });
    const exportedPanel = async () => { await click("Design JSON"); return JSON.parse(await downloads.at(-1).blob.text()); };
    await click("20 HP");
    await click("Jack");
    await setPanelNumber("X from centre", -15);
    await setPanelNumber("Y from centre", 20);
    await setPanelNumber("Hole diameter", 6.5);
    await click("Pot");
    await setPanelNumber("X from centre", 15);
    await setPanelNumber("Y from centre", -20);
    await setPanelNumber("Max panel thickness", 2);
    await click("Select all");
    await click("Align Y");
    let panelData = await exportedPanel();
    assert.deepEqual(panelData.configuration.components.map(c => c.y), [20, 20]);
    assert.match(panelData.warnings.join(" "), /exceeds the specified 2 mm/);
    const editor = document.querySelector(".panel-front-editor");
    await React.act(async () => editor.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "ArrowUp", bubbles: true })));
    panelData = await exportedPanel();
    assert.deepEqual(panelData.configuration.components.map(c => c.y), [21, 21]);
    // Pointer capture keeps a selected group moving together; grid snapping uses the grabbed item.
    const savedPoint = Object.getOwnPropertyDescriptor(globalThis, "DOMPoint");
    Object.defineProperty(globalThis, "DOMPoint", { configurable: true, value: class { constructor(x, y) { this.x = x; this.y = y; } matrixTransform() { return this; } } });
    editor.getScreenCTM = () => ({ inverse: () => ({}) });
    let captured = false;
    editor.setPointerCapture = () => { captured = true; };
    editor.hasPointerCapture = () => captured;
    editor.releasePointerCapture = () => { captured = false; };
    const pointer = (type, x, y) => { const event = new dom.window.MouseEvent(type, { clientX: x, clientY: y, bubbles: true }); Object.defineProperty(event, "pointerId", { value: 1 }); return event; };
    try {
      await React.act(async () => editor.querySelector("[data-item] rect").dispatchEvent(pointer("pointerdown", 0, 0)));
      await React.act(async () => editor.dispatchEvent(pointer("pointermove", 2.4, -4.6)));
      await React.act(async () => editor.dispatchEvent(pointer("pointerup", 2.4, -4.6)));
      panelData = await exportedPanel();
      assert.deepEqual(panelData.configuration.components.map(c => c.x), [-13, 17]);
      assert.deepEqual(panelData.configuration.components.map(c => c.y), [26, 26]);
      assert.equal(captured, false);
      await click("Undo design change");
      panelData = await exportedPanel();
      assert.deepEqual(panelData.configuration.components.map(c => c.x), [-15, 15]);
      assert.deepEqual(panelData.configuration.components.map(c => c.y), [21, 21]);
      await click("Redo design change");
      panelData = await exportedPanel();
      assert.deepEqual(panelData.configuration.components.map(c => c.x), [-13, 17]);

    } finally { if (savedPoint) Object.defineProperty(globalThis, "DOMPoint", savedPoint); else delete globalThis.DOMPoint; }
    await click("Display");
    await setPanelNumber("Opening width", 18);
    await setPanelNumber("Opening height", 10);
    await click("Switch");
    await setPanelNumber("Y from centre", -35);
    await click("Duplicate Switch");
    await click("Remove Switch copy");
    await selectValue(field("Mounting openings"), "slots");
    await toggleSection("Ventilation pattern");
    await click("Panel ventilation");
    await click("Wave");
    panelData = await exportedPanel();
    assert.ok(panelData.ventilation.count > 0);
    assert.equal(panelData.configuration.components.length, 4);
    assert.equal(panelData.configuration.mounting, "slots");
    assert.equal(panelData.configuration.vents.design.layers.length, 2);
    // Use the actual SVG parser, text outlines and fabrication layer controls.
    const upload = document.querySelector('[aria-label="Import panel artwork SVG"]');
    Object.defineProperty(upload, "files", { configurable: true, value: [{ name: "label.svg", size: 150, text: async () => '<svg xmlns="http://www.w3.org/2000/svg"><rect width="20" height="5" /></svg>' }] });
    await React.act(async () => upload.dispatchEvent(new dom.window.Event("change", { bubbles: true })));
    panelData = await exportedPanel();
    assert.equal(panelData.configuration.artwork[0].operation, "engrave");
    assert.equal(panelData.layers.engrave.length, 1);
    await setPanelNumber("Y from centre", 40);
    await selectValue(field("Artwork operation"), "cut");
    panelData = await exportedPanel();
    assert.equal(panelData.layers.engrave.length, 0);
    await selectValue(field("Artwork operation"), "engrave");
    const oldFetch = globalThis.fetch;
    globalThis.fetch = async url => ({ ok: true, json: async () => JSON.parse(readFileSync(path.join(project, "public", url), "utf8")) });
    try { await click("Add text"); } finally { globalThis.fetch = oldFetch; }
    const textInput = field("Text");
    await React.act(async () => {
      Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(textInput, "OUT");
      textInput.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
    });
    await click("Apply text");
    await setPanelNumber("Y from centre", -50);
    panelData = await exportedPanel();
    assert.equal(panelData.configuration.artwork[1].source.text, "OUT");
    assert.equal(panelData.configuration.artwork[1].operation, "engrave");
    await click("Cutting layout");
    await click("Export panel cut and engrave SVG");
    assert.match(downloads.at(-1).name, /panel-3u-20hp.svg$/);
    const panelSvgDoc = new dom.window.DOMParser().parseFromString(await downloads.at(-1).blob.text(), "image/svg+xml");
    assert.equal(document.querySelector('[data-layer="cut"]').getAttribute("d"), panelSvgDoc.querySelector("#panel-cut").getAttribute("d"));
    assert.equal(document.querySelectorAll('[data-layer="engrave"]').length, panelSvgDoc.querySelectorAll("#engrave path").length);
    await selectValue(field("Panel format"), "intellijel-1u");
    panelData = await exportedPanel(); assert.equal(panelData.dimensions.height, 39.65);
    await selectValue(field("Panel format"), "pulp-logic-1u");
    panelData = await exportedPanel(); assert.equal(panelData.dimensions.height, 43.18); assert.equal(panelData.configuration.hp, 18);
    await selectValue(field("Panel format"), "3u");
    await click("Material library");
    await React.act(async () => document.querySelector('.info-dialog:not(.project-dialog) button[aria-label="Green"]').click());
    await selectValue(document.querySelector(".info-dialog:not(.project-dialog) select"), "opaque");
    await click("Close notes");
    await click("Build notes");
    assert.match(document.querySelector(".info-dialog:not(.project-dialog)").textContent, /A face for your next idea/);
    await click("Close notes");
    await click("Synth protector");
    await click("Panel designer");
    panelData = await exportedPanel();
    assert.equal(panelData.configuration.tint.id, "green");
    assert.equal(panelData.configuration.transparency, "opaque");
    assert.equal(panelData.configuration.components.length, 4);
    assert.equal(panelData.configuration.artwork.length, 2);
    await click("Perspective");
    assert.equal(button("Perspective").getAttribute("aria-pressed"), "true");

    await click("Synth stand");
    assert.equal(button("35°").getAttribute("aria-pressed"), "true");
    assert.equal(button("Front extension").getAttribute("aria-checked"), "true");
    await click("Front extension");
    assert.equal(document.querySelector('input[aria-label="Extension length in mm"]'), null);
    await click("Design JSON");
    const compactStand = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(compactStand.configuration.transparency, "opal", "Case edits preserve stand finish");
    assert.equal(compactStand.frontExtension.length, 0);
    assert.equal(compactStand.configuration.frontExtensionLength, 15);
    assert.equal(button("Rounded edges").getAttribute("aria-checked"), "true");
    await click("Rounded edges");
    assert.equal(document.querySelector('input[aria-label="Corner radius in mm"]'), null);
    assert.equal(button("Cable holes in braces").getAttribute("aria-checked"), "true");
    await click("Cable holes in braces");
    assert.equal(document.querySelector('input[aria-label="Cable hole diameter in mm"]'), null);
    await click("Export stand design JSON");
    const standardStand = JSON.parse(await downloads.at(-1).blob.text());
    await click("Advanced · diagonal");
    assert.equal(button("Advanced · diagonal").getAttribute("aria-pressed"), "true");
    assert.equal(document.querySelector('input[aria-label="Diagonal sweep in °"]'), null);
    assert.match(document.querySelector(".stand-mode-control").textContent, /every crossing stays at 90°/);
    await click("Export stand design JSON");
    const diagonalStand = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(diagonalStand.configuration.advancedMode, true);
    assert.ok(diagonalStand.diagonal.angle > 0);
    assert.equal(diagonalStand.construction.slotWidth, standardStand.construction.slotWidth);
    assert.equal(diagonalStand.diagonal.intersectionAngle, 90);
    assert.equal(diagonalStand.construction.braceCount, 4);
    await click("Cutting layout");
    const diagonalPaths = [...document.querySelectorAll(".stand-cutting-layout path")].map(p => p.getAttribute("d"));
    await click("Export stand sheets as SVG");
    const diagonalSvg = new dom.window.DOMParser().parseFromString(await downloads.at(-1).blob.text(), "image/svg+xml");
    assert.deepEqual(diagonalPaths, [...diagonalSvg.querySelectorAll("path")].map(p => p.getAttribute("d")));
    await click("Synth protector");
    await click("Synth stand");
    assert.equal(button("Advanced · diagonal").getAttribute("aria-pressed"), "true");
    await click("Standard");
    assert.equal(document.querySelector('input[aria-label="Diagonal sweep in °"]'), null);
    await click("Export stand design JSON");
    assert.deepEqual(JSON.parse(await downloads.at(-1).blob.text()).parts, standardStand.parts);
    // Keep real parsing, fitting and controls; emulate only the worker transport.
    previous.set("Worker", Object.getOwnPropertyDescriptor(globalThis, "Worker"));
    const { createSynthStand } = load(path.join(project, "lib/synth-stand.ts"));
    const { createSynthProtector } = load(path.join(project, "lib/synth-protector.ts"));
    let fittingJobs = 0;
    globalThis.Worker = class {
      terminated = false;
      postMessage(configuration) {
        fittingJobs++;
        setTimeout(() => {
          if (this.terminated) return;
          try { this.onmessage({ data: "headroom" in configuration ? { protector: createSynthProtector(configuration) } : { stand: createSynthStand(configuration) } }); }
          catch (error) { this.onmessage({ data: { error: error.message } }); }
        }, 0);
      }
      terminate() { this.terminated = true; }
    };
    const objText = "v -300 -40 -150\nv 300 -40 -150\nv 300 40 -150\nv -300 40 -150\nv -300 -40 150\nv 300 -40 150\nv 300 40 150\nv -300 40 150\nf 1 2 3 4\nf 5 8 7 6\nf 1 5 6 2\nf 4 3 7 8\nf 1 4 8 5\nf 2 6 7 3\n";
    const modelUpload = document.querySelector('.stand-object-file');
    Object.defineProperty(modelUpload, "files", { configurable: true, value: [{ name: "my-synth.obj", size: objText.length, text: async () => objText }] });
    await React.act(async () => modelUpload.dispatchEvent(new dom.window.Event("change", { bubbles: true })));
    assert.equal(button("Export stand sheets as SVG").disabled, true, "Export waits for the current fit");
    const settleFit = async () => React.act(async () => new Promise(resolve => setTimeout(resolve, 180)));
    await settleFit();
    assert.equal(button("Export stand sheets as SVG").disabled, false);
    assert.equal(document.querySelector('input[aria-label="Synth width in mm"]'), null);
    await click("Export stand design JSON");
    let fitted = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(fitted.configuration.width, 600);
    assert.equal(fitted.objectFit.name, "my-synth.obj");
    const jobsBeforeAppearance = fittingJobs;
    await click("Material library");
    await React.act(async () => document.querySelector('.info-dialog:not(.project-dialog) button[aria-label="Green"]').click());
    await click("Close notes");
    assert.equal(button("Export stand sheets as SVG").disabled, false, "Appearance edits keep fitted export ready");
    await settleFit();
    assert.equal(fittingJobs, jobsBeforeAppearance, "Appearance changes must not restart model fitting");
    await click("Download project");
    const fittedProject = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(fittedProject.format, "acryl508-project");
    assert.ok(fittedProject.designs.stand.object.vertices.length > 0);
    assert.equal(fittedProject.designs.stand.tint.id, "green");

    await click("15°");
    await settleFit();
    await click("Export stand design JSON");
    fitted = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(fitted.configuration.angle, 15);
    await click("Cutting layout");
    const fittedPaths = [...document.querySelectorAll(".stand-cutting-layout path")].map(p => p.getAttribute("d"));
    await click("Export stand sheets as SVG");
    const fittedSvg = new dom.window.DOMParser().parseFromString(await downloads.at(-1).blob.text(), "image/svg+xml");
    assert.deepEqual(fittedPaths, [...fittedSvg.querySelectorAll("path")].map(p => p.getAttribute("d")));
    const modelUnits = document.querySelector('.stand-object-settings select');
    await selectValue(modelUnits, "m");
    await settleFit();
    assert.match(document.querySelector('[role="alert"]').textContent, /units/);
    assert.equal(button("Export stand sheets as SVG").disabled, true);
    await selectValue(modelUnits, "mm");
    await settleFit();
    await click("Synth protector");
    await click("Synth stand");
    assert.match(document.querySelector('.stand-object-name').textContent, /my-synth.obj/);
    await click("Remove 3D model");
    assert.equal(document.querySelector('input[aria-label="Synth width in mm"]').value, "550");
    assert.equal(button("Export stand sheets as SVG").disabled, false);
    await click("Export stand design JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).objectFit, null);
    await click("Synth protector");
    assert.equal(document.querySelector('.stand-object-name'), null, "Models are independent between modes");
    const protectorUpload = document.querySelector('.stand-object-file');
    Object.defineProperty(protectorUpload, "files", { configurable: true, value: [{ name: "protector-synth.obj", size: objText.length, text: async () => objText }] });
    await React.act(async () => protectorUpload.dispatchEvent(new dom.window.Event("change", { bubbles: true })));
    assert.equal(button("Export protector sheets as SVG").disabled, true);
    await settleFit();
    assert.equal(button("Export protector sheets as SVG").disabled, false);
    assert.equal(document.querySelector('input[aria-label="Synth width in mm"]'), null);
    await click("25°");
    await settleFit();
    await click("Export protector design JSON");
    const modelProtector = JSON.parse(await downloads.at(-1).blob.text());
    assert.equal(modelProtector.objectFit.name, "protector-synth.obj");
    assert.equal(modelProtector.configuration.width, 600);
    assert.equal(modelProtector.configuration.angle, 25);
    assert.equal(modelProtector.configuration.headroom, 50);
    await click("Cutting layout");
    const protectorPaths = [...document.querySelectorAll(".stand-cutting-layout path")].map(p => p.getAttribute("d"));
    await click("Export protector sheets as SVG");
    const protectorSvg = new dom.window.DOMParser().parseFromString(await downloads.at(-1).blob.text(), "image/svg+xml");
    assert.deepEqual(protectorPaths, [...protectorSvg.querySelectorAll("path")].map(p => p.getAttribute("d")));
    const protectorUnits = document.querySelector('.stand-object-settings select');
    await selectValue(protectorUnits, "m");
    await settleFit();
    assert.match(document.querySelector('[role="alert"]').textContent, /units/);
    assert.equal(button("Export protector sheets as SVG").disabled, true);
    const beforeInvalidExport = downloads.length;
    await click("Design JSON");
    assert.equal(downloads.length, beforeInvalidExport, "The single design JSON action also guards failed fits");
    await selectValue(protectorUnits, "mm");
    await settleFit();
    await click("Synth stand");
    assert.equal(document.querySelector('.stand-object-name'), null);
    await click("Synth protector");
    assert.match(document.querySelector('.stand-object-name').textContent, /protector-synth.obj/);
    await click("Remove 3D model");
    assert.equal(document.querySelector('input[aria-label="Synth width in mm"]').value, "550");
    await click("Export protector design JSON");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).objectFit, null);
    await click("Synth stand");
    await click("Build notes");
    assert.match(document.querySelector(".info-dialog:not(.project-dialog)").textContent, /Slot together\. Play at your angle/);
    assert.match(document.querySelector(".info-dialog:not(.project-dialog)").textContent, /no load capacity or stability rating/);
    await click("Close notes");
    // Each multi-sheet designer exposes and persists the same optional material controls.
    for (const [modeLabel, mode, materialSection, thickness] of [["Speaker case", "speaker", "Acrylic sheets", 6.5], ["Art mode", "art", "Grid & material", 5.5], ["Synth protector", "protector", "Material & construction", 8.5], ["Synth stand", "stand", "Material & fit", 9.5]]) {
      await click(modeLabel);
      if (!section(materialSection).open) await toggleSection(materialSection);
      assert.equal(button("Use individual acrylic materials for each sheet").getAttribute("aria-checked"), "false");
      await click("Use individual acrylic materials for each sheet");
      const materialRow = () => document.querySelector(".panel-material");
      await selectValue(materialRow().querySelector("select"), "blue");
      await selectValue(materialRow().querySelectorAll("select")[1], "opaque");
      await React.act(async () => {
        const input = materialRow().querySelector('input[type="number"]');
        Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(input, String(thickness));
        input.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
      });
      await click("Design JSON");
      const data = JSON.parse(await downloads.at(-1).blob.text()), id = data.parts[0].id;
      assert.equal(data.configuration.individualSheetMaterials, true);
      assert.equal(data.configuration.sheetTints[id].id, "blue");
      assert.equal(data.configuration.sheetTransparencies[id], "opaque");
      assert.equal(data.parts[0].thickness, thickness);
      await click("Cutting layout");
      const path = document.querySelector(`.stand-cutting-layout [data-part="${id}"] path`);
      assert.equal(path.getAttribute("fill"), "#15a8dc");
      assert.equal(path.getAttribute("fill-opacity"), "1");
      await click("Use individual acrylic materials for each sheet");
      assert.equal(document.querySelector(".panel-material"), null);
      await click("Use individual acrylic materials for each sheet");
      assert.equal(materialRow().querySelector("select").value, "blue");
      assert.equal(materialRow().querySelector("input").value, String(thickness));
      await click("Material library");
      await React.act(async () => document.querySelector('.info-dialog:not(.project-dialog) button[aria-label="Red"]').click());
      await click("Close notes");
      assert.equal(materialRow().querySelector("select").value, "red", "Library color applies to every sheet");
      assert.equal(materialRow().querySelectorAll("select")[1].value, "opaque");
      await click("Undo design change");
      assert.equal(materialRow().querySelector("select").value, "blue");
      await click("Panel designer");
      await click(modeLabel);
      assert.equal(materialRow().querySelector("select").value, "blue", `${mode} choices survive mode switching`);
    }
    await click("Synth stand");
    await click("Download project");
    const projectBackup = await downloads.at(-1).blob.text();
    const projectData = JSON.parse(projectBackup);
    assert.equal(projectData.designs.case.hp, 104);
    assert.equal(projectData.designs.panel.components.length, 4);
    for (const mode of ["speaker", "art", "stand", "protector"]) assert.equal(projectData.designs[mode].individualSheetMaterials, true);
    await click("Save copy");
    // IndexedDB commits asynchronously; wait for the operation, not a fixed UI state assumption.
    await React.act(async () => new Promise(resolve => setTimeout(resolve, 30)));
    await click("Case designer");
    await click("84");
    await click("Open");
    await React.act(async () => new Promise(resolve => setTimeout(resolve, 30)));
    assert.equal(document.querySelector('.project-dialog').open, true);
    await click("Open project");
    await React.act(async () => new Promise(resolve => setTimeout(resolve, 30)));
    await click("Case designer");
    assert.equal(button("104").getAttribute("aria-pressed"), "true", "Named project restores the saved case");
    await click("84");
    const projectUpload = document.querySelector('input[aria-label="Import project JSON"]');
    Object.defineProperty(projectUpload, "files", { configurable: true, value: [{ name: "backup.json", size: projectBackup.length, text: async () => projectBackup }] });
    await React.act(async () => projectUpload.dispatchEvent(new dom.window.Event("change", { bubbles: true })));
    await click("Case designer");
    assert.equal(button("104").getAttribute("aria-pressed"), "true", "Project JSON restores the saved case");
    assert.equal(button("Undo design change").disabled, true, "Opening a project starts a fresh history");
    const beforeInvalidImport = JSON.stringify(projectData.designs);
    Object.defineProperty(projectUpload, "files", { configurable: true, value: [{ name: "bad.json", size: 2, text: async () => "{}" }] });
    await React.act(async () => projectUpload.dispatchEvent(new dom.window.Event("change", { bubbles: true })));
    assert.match(document.querySelector('.project-toolbar [role="alert"]').textContent, /Choose an Acryl508/);
    await click("Download project");
    assert.deepEqual(JSON.parse(await downloads.at(-1).blob.text()).designs.panel, JSON.parse(beforeInvalidImport).panel);
    // Remount against the same database to exercise actual recovery.
    await React.act(async () => new Promise(resolve => setTimeout(resolve, 850)));
    await React.act(async () => root.render(null));
    await React.act(async () => root.render(React.createElement(ConfiguratorShell)));
    await React.act(async () => new Promise(resolve => setTimeout(resolve, 30)));
    await click("Case designer");
    assert.equal(button("104").getAttribute("aria-pressed"), "true", "Autosave restores after remount");
    await click("Download project");
    const recoveredMaterials = JSON.parse(await downloads.at(-1).blob.text());
    for (const mode of ["speaker", "art", "stand", "protector"]) {
      assert.deepEqual(recoveredMaterials.designs[mode].sheetTints, projectData.designs[mode].sheetTints);
      assert.deepEqual(recoveredMaterials.designs[mode].sheetTransparencies, projectData.designs[mode].sheetTransparencies);
      assert.deepEqual(recoveredMaterials.designs[mode].sheetThicknesses, projectData.designs[mode].sheetThicknesses);
    }
    const opentype = require("opentype.js");
    const glyphPath = new opentype.Path(); glyphPath.moveTo(0, 0); glyphPath.lineTo(500, 0); glyphPath.lineTo(500, 700); glyphPath.lineTo(0, 700); glyphPath.close();
    const testFont = new opentype.Font({ familyName: "Case Font", styleName: "Regular", unitsPerEm: 1000, ascender: 800, descender: -200, glyphs: [new opentype.Glyph({ name: ".notdef", advanceWidth: 600, path: new opentype.Path() }), new opentype.Glyph({ name: "A", unicode: 65, advanceWidth: 600, path: glyphPath })] });
    const fontBytes = testFont.toArrayBuffer();
    const fontProject = structuredClone(projectData);
    fontProject.mode = "case";
    fontProject.fonts = [{ id: "case-font", name: "Case Font", data: Buffer.from(fontBytes).toString("base64") }];
    fontProject.designs.case.cutouts = [{ id: "editable-text", name: "A", source: { kind: "text", text: "A", fontId: "case-font", fontName: "Case Font" }, polygons: [[[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]], side: "front", x: 0, y: 0, width: 20, rotation: 0 }];
    const fontSource = JSON.stringify(fontProject);
    const recoveredUpload = document.querySelector('input[aria-label="Import project JSON"]');
    Object.defineProperty(recoveredUpload, "files", { configurable: true, value: [{ name: "font-project.json", size: fontSource.length, text: async () => fontSource }] });
    await React.act(async () => recoveredUpload.dispatchEvent(new dom.window.Event("change", { bubbles: true })));
    await click("Synth stand");
    await click("Case designer");
    const fontSelect = document.querySelector('.cutout-text-editor select');
    assert.equal(fontSelect.value, "case-font", "Imported font remains selected after switching modes");
    const recoveredTextInput = document.querySelector('.cutout-text-editor input');
    await React.act(async () => {
      Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value").set.call(recoveredTextInput, "AAA");
      recoveredTextInput.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
    });
    await click("Apply text");
    await click("Design JSON");
    const editedText = JSON.parse(await downloads.at(-1).blob.text()).configuration.cutouts[0];
    assert.equal(editedText.source.text, "AAA");
    assert.equal(editedText.source.fontId, "case-font");
    await click("Panel designer");
    await click("Download project");
    assert.equal(JSON.parse(await downloads.at(-1).blob.text()).fonts[0].data, fontProject.fonts[0].data);


  } finally {
    await React.act(async () => root.unmount());
    URL.createObjectURL = originalCreate; URL.revokeObjectURL = originalRevoke;
    for (const [key, descriptor] of previous) { if (descriptor) Object.defineProperty(globalThis, key, descriptor); else delete globalThis[key]; }
    dom.window.close();
  }
});
