"use client";
import { lazy, Suspense, useId, useState, type CSSProperties } from "react";
import { ArrowDownToLine, Box, Check, Layers2, Maximize, Minimize, RotateCcw, Shuffle } from "lucide-react";
import { ConfigSection } from "./config-section";
import { SheetMaterialControls, SheetMaterialSwatches } from "./sheet-material-controls";
import { allSheetMaterials, sheetMaterial, sheetMaterialSummary, sheetThicknessLabel } from "@/lib/sheet-materials";
import { FabricationButton } from "./fabrication-button";
import { artLimits, artSheetLayout, type Art, type ArtConfiguration, type ArtOverride } from "@/lib/art";
import { standPathData } from "@/lib/synth-stand";
import type { ArtView } from "./art-preview";
const ArtPreview = lazy(() => import("./art-preview").then(module => ({ default: module.ArtPreview })));
function Slider({ label, value, min, max, step = 1, unit = "", onChange }: { label: string; value: number; min: number; max: number; step?: number; unit?: string; onChange: (value: number) => void }) {
  const id = useId();
  return <div className="range-field"><div className="field-heading"><label htmlFor={id}>{label}</label><div className="number-field"><input type="number" aria-label={`${label}${unit ? ` in ${unit}` : ""}`} min={min} max={max} step={step} value={Number(value.toFixed(2))} onChange={event => { const next = event.currentTarget.valueAsNumber; if (Number.isFinite(next)) onChange(Math.max(min,Math.min(max,next))); }} /><span>{unit}</span></div></div><input id={id} className="range-input" type="range" min={min} max={max} step={step} value={value} style={{ "--range-progress": `${(value-min)/(max-min)*100}%` } as CSSProperties} onChange={event => onChange(event.currentTarget.valueAsNumber)} /><div className="range-labels"><span>{min}{unit}</span><span>{max}{unit}</span></div></div>;
}
function CuttingLayout({ art }: { art: Art }) {
  const layout = artSheetLayout(art);
  return <div className="stand-cutting-layout"><svg viewBox={`0 0 ${layout.width} ${layout.height}`} role="img" aria-label={`Art cutting layout: ${art.parts.length} slotted sheets`}>{layout.parts.map(({part,x,y}) => <g key={part.id} data-part={part.id} transform={`translate(${x} ${y})`}><title>{part.label} · {part.width.toFixed(1)} × {part.height.toFixed(1)} mm</title><path d={standPathData(part.polygons)} fill={sheetMaterial(art.config, part.id).tint.color} fillOpacity={sheetMaterial(art.config, part.id).transparency === "opaque" ? 1 : sheetMaterial(art.config, part.id).transparency === "opal" ? 0.75 : 0.4} stroke="currentColor" strokeWidth={1} vectorEffect="non-scaling-stroke" fillRule="evenodd" />{part.bend && <path d={`M${-part.leafWidth/2} ${-part.bend.start*100}H${part.leafWidth/2}`} fill="none" stroke="#2563eb" strokeDasharray="3 3" vectorEffect="non-scaling-stroke" />}</g>)}</svg><p>{art.parts.length} sheets · {layout.width.toFixed(0)} × {layout.height.toFixed(0)} mm · Blue dashed lines mark bend starts</p></div>;
}
type Props = { art: Art; dark: boolean; onChange: (patch: Partial<ArtConfiguration>) => void; onExportJson: () => void; onExportSvg: () => void; onOpenFabrication: () => void };
export function ArtDesigner({ art, dark, onChange, onExportJson, onExportSvg, onOpenFabrication }: Props) {
  const config = art.config;
  const [view,setView] = useState<ArtView>("perspective"), [layout,setLayout] = useState(false), [exploded,setExploded] = useState(false), [expanded,setExpanded] = useState(false), [resetKey,setResetKey] = useState(0), [selected,setSelected] = useState("a-1");
  const sheet = art.parts.find(part => part.id === selected) ?? art.parts[0];
  const dimension = (label: string, field: keyof typeof artLimits, unit = "", step = 1) => <Slider label={label} value={config[field]} {...artLimits[field]} unit={unit} step={step} onChange={value => onChange(field === "thickness" ? allSheetMaterials(config, { thickness: value }) : { [field]: value })} />;
  const override = (field: keyof ArtOverride, value: number) => onChange({ sheets: { ...config.sheets, [sheet.id]: { ...config.sheets[sheet.id], [field]: value } } });
  return <div className="configurator-grid art-designer"><div className="preview-column">
    <section className={`preview-stage ${expanded ? "preview-expanded" : ""}`} aria-label="Art preview" onKeyDown={event => { if (event.key === "Escape") setExpanded(false); }}>
      <div className="stage-topline"><div className="model-label"><span className="status-dot" /><span>ART STUDY</span><span className="model-label-separator">/</span><span>{art.parts.length} SHEETS · SEED {config.seed}</span></div><span className="stage-material">GS—{sheetThicknessLabel(config, art.parts)} <span>•</span> {sheetMaterialSummary(config).toUpperCase()}</span></div>
      <div className="stage-watermark" aria-hidden="true">A-508</div>
      <div className="canvas-wrap">{layout ? <CuttingLayout art={art} /> : <Suspense fallback={<div className="preview-fallback" role="status">Growing your sculpture…</div>}><ArtPreview art={art} dark={dark} exploded={exploded} view={view} resetKey={resetKey} /></Suspense>}</div>
      <div className="stage-side-tools"><button className={`icon-button ${exploded && !layout ? "tool-active" : ""}`} aria-label="Exploded art view" aria-pressed={exploded && !layout} title="Exploded view" onClick={() => { setLayout(false); setExploded(!exploded); }}><Layers2 size={18} /></button><span /><button className="icon-button" aria-label="Reset art camera" title="Reset camera" onClick={() => { setLayout(false); setView("perspective"); setResetKey(key => key+1); }}><RotateCcw size={16} /></button><button className="icon-button" aria-label={expanded ? "Exit expanded art preview" : "Expand art preview"} onClick={() => setExpanded(!expanded)}>{expanded ? <Minimize size={16} /> : <Maximize size={16} />}</button></div>
      <div className="stage-bottom"><div className="view-control" role="group" aria-label="Art view">{(["perspective","side","top"] as const).map(option => <button key={option} className={!layout && view === option ? "view-active" : ""} aria-pressed={!layout && view === option} onClick={() => { setLayout(false); setView(option); }}>{option === "perspective" && <Box size={13} />}{option === "perspective" ? "Perspective" : option === "side" ? "Side" : "Top"}</button>)}<button className={layout ? "view-active" : ""} aria-pressed={layout} onClick={() => setLayout(true)}>Cutting layout</button></div><span className="stage-hint">{layout ? "Full-size SVG available below" : "Drag to orbit · Scroll to zoom"}</span></div>
      <div className="stage-caption"><span><Check size={12} />{layout ? "Flat patterns include bend allowance" : exploded ? "Lower family A into family B, then form the leaves" : "Slotted roots · outward-growing leaves"}</span><span>PROTOTYPE · MM</span></div>
    </section>
    <section className="summary-panel" aria-label="Art specification"><div className="summary-title"><span className="micro-label">ART SPECIFICATION</span><h2>A508 <span>/</span> {art.parts.length} sheets</h2></div><dl className="spec-list"><div><dt>Grid footprint</dt><dd>{config.width.toFixed(0)} × {config.depth.toFixed(0)} <small>mm</small></dd></div><div><dt>Formed envelope</dt><dd>{art.dimensions.width.toFixed(0)} × {art.dimensions.depth.toFixed(0)} × {art.dimensions.height.toFixed(0)} <small>mm</small></dd></div><div><dt>Construction</dt><dd>{config.rows} + {config.columns} slotted sheets</dd></div><div><dt>Material</dt><dd><SheetMaterialSwatches config={config} parts={art.parts} /></dd></div></dl><div className="summary-actions"><FabricationButton onClick={onOpenFabrication} /><button className="button button-dark summary-export" aria-label="Export art design JSON" onClick={onExportJson}><ArrowDownToLine size={15} />Design JSON</button><button className="button button-orange summary-export" aria-label="Export art sheets as SVG" onClick={onExportSvg}><ArrowDownToLine size={15} />SVG sheets</button></div></section>
  </div><aside className="control-panel accordion-control-panel" aria-label="Art controls"><div className="panel-heading"><h2>Grow something unexpected</h2><span className="micro-label">01—05</span></div><p className="config-intro">A slotted grid. A little variation. Your own acrylic botany.</p>
    <ConfigSection number="01" title="Growth" summary={`${config.height} mm · ${config.variation}% variation · Seed ${config.seed}`} defaultOpen>
      {dimension("Growth height","height","mm")}{dimension("Height variation","variation","%")}{dimension("Centre crown","crown","%")}
      <p className="control-note">Raise the crown for taller inner leaves. Variation adds repeatable differences to each sheet.</p>
      {dimension("Pattern seed","seed")}
      <button className="cutout-button" onClick={() => onChange({ seed: config.seed % 9999 + 1 })}><Shuffle size={14} />New growth pattern</button><p className="control-note">A new seed changes the generated sheets. Individual overrides stay fixed.</p>
    </ConfigSection>
    <ConfigSection number="02" title="Outward bends" summary={config.bends ? `${config.bendAngle}° · starts at ${config.bendLocation}%` : "Off · straight leaves"}>
      <div className="inline-field"><label htmlFor="art-bends">Bend the leaves</label><button id="art-bends" className={`toggle ${config.bends ? "toggle-on" : ""}`} role="switch" aria-checked={config.bends} aria-label="Bend the leaves" onClick={() => onChange({ bends: !config.bends })}><span /></button></div>
      {config.bends && <>{dimension("Bend angle","bendAngle","°")}{dimension("Bend location","bendLocation","%")}{dimension("Bend variation","bendVariation","%")}</>}
      <p className="control-note">Location runs from the leaf root toward its tip. Every bend points away from the centre and stays above the joints.</p>
    </ConfigSection>
    <ConfigSection number="03" title="Grid & material" summary={`${config.rows} × ${config.columns} grid · ${sheetThicknessLabel(config, art.parts)} mm GS`}>
      {dimension("Grid width","width","mm")}{dimension("Grid depth","depth","mm")}{dimension("Family A sheets","rows","",2)}{dimension("Family B sheets","columns","",2)}
      <p className="control-note">Sheets come in pairs to keep a clear central bay. The footprint expands when needed to preserve material beside the slots.</p>
      <SheetMaterialControls config={config} parts={art.parts} limits={artLimits.thickness} label="Art acrylic color" onChange={onChange} />
      {dimension(config.individualSheetMaterials ? "Apply thickness to all sheets" : "Sheet thickness","thickness","mm",0.1)}{dimension("Slot clearance","clearance","mm",0.05)}<p className="control-note">{config.individualSheetMaterials ? "Slots fit each adjoining sheet" : `${art.slotWidth.toFixed(2)} mm slots`} · {art.baseHeight.toFixed(0)} mm root grid. Use measured sheet thickness and test a fit coupon.</p>
    </ConfigSection>
    <ConfigSection number="04" title="Individual sheets" summary={`${Object.keys(config.sheets).length} overrides`}>
      <div className="inline-field"><label htmlFor="art-sheet">Sheet to adjust</label><select id="art-sheet" value={sheet.id} onChange={event => setSelected(event.target.value)}>{art.parts.map(part => <option key={part.id} value={part.id}>{part.label}{config.sheets[part.id] ? " · adjusted" : ""}</option>)}</select></div>
      <p className="control-note">A runs left to right; B runs front to back. Numbering follows each family from its negative side to its positive side.</p>
      <Slider label="Sheet height" value={sheet.settings.height} {...artLimits.height} unit="mm" onChange={value => override("height",value)} />
      {config.bends && <><Slider label="Sheet bend angle" value={sheet.settings.bendAngle} {...artLimits.bendAngle} unit="°" onChange={value => override("bendAngle",value)} /><Slider label="Sheet bend location" value={sheet.settings.bendLocation} {...artLimits.bendLocation} unit="%" onChange={value => override("bendLocation",value)} /></>}
      <button className="cutout-button" disabled={!config.sheets[sheet.id]} onClick={() => { const sheets = { ...config.sheets }; delete sheets[sheet.id]; onChange({ sheets }); }}>Reset this sheet</button><button className="cutout-button" disabled={!Object.keys(config.sheets).length} onClick={() => onChange({ sheets: {} })}>Reset all sheets</button>
    </ConfigSection>
    <ConfigSection number="05" title="Your parts" summary={`${art.parts.length} sheets · no hardware`}><div className="stand-parts">{art.parts.map(part => <div key={part.id}><strong>1×</strong><span>{part.label}<small>{part.width.toFixed(0)} × {part.height.toFixed(1)} mm flat · {part.bend ? `${part.settings.bendAngle.toFixed(1)}° outward` : "straight"}</small></span></div>)}</div><p className="control-note">Assemble B slots-up and A slots-down, then form the leaves. Dashed bend-start guides are separate from SVG cut paths. Prototype the forming sequence, fit and stability; leaf collisions are not simulated.</p><div className="hardware-note"><span className="hardware-dot" />Acrylic only <span>Slot together · no glue</span></div></ConfigSection>
  </aside></div>;
}
