"use client";
import { lazy, Suspense, useId, useState, type CSSProperties } from "react";
import { ArrowDownToLine, Box, Check, Layers2, Maximize, Minimize, RotateCcw, SlidersHorizontal } from "lucide-react";
import { ConfigSection } from "@/components/config-section";
import { materialLabel } from "@/lib/acrylic-material";
import { ColorChooser, TransparencyChooser, MaterialPreviewNote } from "@/components/material-controls";
import { protectorLimits, protectorSupportLimits, protectorSheetLayout, type ProtectorConfiguration, type SynthProtector } from "@/lib/synth-protector";
import { standPathData } from "@/lib/synth-stand";
import type { StandView } from "@/components/stand-preview";
const ProtectorPreview = lazy(() => import("@/components/protector-preview").then(module => ({ default: module.ProtectorPreview })));

function Dimension({ label, field, config, onChange, unit = "mm", step = 1 }: { label: string; field: keyof typeof protectorLimits; config: ProtectorConfiguration; onChange: (patch: Partial<ProtectorConfiguration>) => void; unit?: string; step?: number }) {
  const id = useId(), value = config[field], limits = protectorSupportLimits(config);
  const min = field === "footInset" ? limits.insetMin : protectorLimits[field].min;
  const max = field === "footInset" ? limits.insetMax : field === "sideExtraFeet" ? limits.sideExtraMax : field === "endExtraFeet" ? limits.endExtraMax : protectorLimits[field].max;
  const [draft, setDraft] = useState<string | null>(null);
  function commit() {
    if (draft?.trim() && Number.isFinite(Number(draft))) onChange({ [field]: Math.max(min, Math.min(max, Number(draft))) });
    setDraft(null);
  }
  return <div className="range-field"><div className="field-heading"><label htmlFor={id}>{label}</label><div className="number-field"><input aria-label={`${label} in ${unit}`} type="number" min={min} max={max} step={step} value={draft ?? value} onFocus={() => setDraft(String(value))} onChange={event => { setDraft(event.target.value); const next = Number(event.target.value); if (event.target.value && Number.isFinite(next) && next >= min && next <= max) onChange({ [field]: next }); }} onBlur={commit} onKeyDown={event => { if (event.key === "Enter") event.currentTarget.blur(); }} /><span>{unit}</span></div></div><input id={id} className="range-input" type="range" min={min} max={max} step={step} value={value} style={{ "--range-progress": `${(value - min) / Math.max(1, max - min) * 100}%` } as CSSProperties} onChange={event => onChange({ [field]: event.currentTarget.valueAsNumber })} /><div className="range-labels"><span>{min} {unit}</span><span>{max} {unit}</span></div></div>;
}
function CuttingLayout({ protector }: { protector: SynthProtector }) {
  const layout = protectorSheetLayout(protector);
  return <div className="stand-cutting-layout"><svg viewBox={`0 0 ${layout.width} ${layout.height}`} role="img" aria-label={`Cutting layout: one top sheet, ${protector.footCount} locating feet and ${protector.stripCount} retaining strips`}>
    {layout.parts.map(({ part, x, y }) => <g key={part.id} transform={`translate(${x} ${y})`}><title>{part.label}: {part.width.toFixed(1)} × {part.height.toFixed(1)} mm</title><path d={standPathData(part.polygons)} fill={protector.config.tint.color} fillOpacity={0.4} stroke="currentColor" strokeWidth={1} vectorEffect="non-scaling-stroke" fillRule="evenodd" /></g>)}
  </svg><p>All {protector.parts.length} parts · {layout.width.toFixed(0)} × {layout.height.toFixed(0)} mm layout · arrange to fit your stock sheet</p></div>;
}
type Props = { protector: SynthProtector; dark: boolean; onChange: (patch: Partial<ProtectorConfiguration>) => void; onExportJson: () => void; onExportSvg: () => void };
export function ProtectorDesigner({ protector, dark, onChange, onExportJson, onExportSvg }: Props) {
  const config = protector.config;
  const [view, setView] = useState<StandView>("perspective");
  const [layout, setLayout] = useState(false), [exploded, setExploded] = useState(false), [instrument, setInstrument] = useState(true);
  const [expanded, setExpanded] = useState(false), [resetKey, setResetKey] = useState(0);
  return <div className="configurator-grid stand-designer"><div className="preview-column">
    <section className={`preview-stage ${expanded ? "preview-expanded" : ""}`} aria-label="Synth protector preview" onKeyDown={event => { if (event.key === "Escape") setExpanded(false); }}>
      <div className="stage-topline"><div className="model-label"><span className="status-dot" /><span>SYNTH PROTECTOR</span><span className="model-label-separator">/</span><span>{config.headroom} MM CLEARANCE · {protector.parts.length} PARTS</span></div><span className="stage-material">GS—{config.thickness} <span>•</span> {materialLabel(config.tint, config.transparency).toUpperCase()}</span></div>
      <div className="stage-watermark" aria-hidden="true">P—508</div>
      <div className="canvas-wrap">{layout ? <CuttingLayout protector={protector} /> : <Suspense fallback={<div className="preview-fallback" role="status">Preparing your protector…</div>}><ProtectorPreview protector={protector} dark={dark} exploded={exploded} instrument={instrument} view={view} resetKey={resetKey} /></Suspense>}</div>
      <div className="stage-side-tools"><button className={`icon-button ${exploded && !layout ? "tool-active" : ""}`} aria-label="Exploded protector view" aria-pressed={exploded && !layout} title="Exploded view" onClick={() => { setLayout(false); setExploded(!exploded); }}><Layers2 size={18} /></button><button className={`icon-button ${instrument && !layout ? "tool-active" : ""}`} aria-label="Show synth envelope" aria-pressed={instrument && !layout} title="Show synth envelope" onClick={() => { setLayout(false); setInstrument(!instrument); }}><SlidersHorizontal size={18} /></button><span /><button className="icon-button" aria-label="Reset protector camera" title="Reset camera" onClick={() => { setView("perspective"); setLayout(false); setResetKey(key => key + 1); }}><RotateCcw size={16} /></button><button className="icon-button" aria-label={expanded ? "Exit expanded protector preview" : "Expand protector preview"} title="Expand preview" onClick={() => setExpanded(!expanded)}>{expanded ? <Minimize size={16} /> : <Maximize size={16} />}</button></div>
      <div className="stage-bottom"><div className="view-control" role="group" aria-label="Protector view">{(["perspective", "side", "top"] as const).map(option => <button key={option} className={!layout && view === option ? "view-active" : ""} aria-pressed={!layout && view === option} onClick={() => { setLayout(false); setView(option); }}>{option === "perspective" && <Box size={13} />}{option === "perspective" ? "Perspective" : option === "side" ? "Side" : "Top"}</button>)}<button className={layout ? "view-active" : ""} aria-pressed={layout} onClick={() => setLayout(true)}>Cutting layout</button></div><span className="stage-hint">{layout ? "Full-size SVG available below" : "Drag to orbit · Scroll to zoom"}</span></div>
      <div className="stage-caption"><span><Check size={12} />{layout ? "Shared preview & export geometry" : instrument ? "Illustrative synth · 12 mm knobs" : exploded ? config.lockingStrips ? "Remove strips, then lift the cover" : "Lower the sheet onto the foot tabs" : `${protector.footCount} feet · ${protector.stripCount} retaining strips`}</span><span>PROTOTYPE · MM</span></div>
    </section>
    <section className="summary-panel" aria-label="Protector specification"><div className="summary-title"><span className="micro-label">PROTECTOR SPECIFICATION</span><h2>P508 <span>/</span> {config.headroom} mm</h2></div><dl className="spec-list"><div><dt>Footprint</dt><dd>{protector.dimensions.width.toFixed(0)} × {protector.dimensions.depth.toFixed(0)} <small>mm</small></dd></div><div><dt>Construction</dt><dd>{protector.footCount} feet{protector.stripCount > 0 ? ` + ${protector.stripCount} strips` : " + cover"}</dd></div><div><dt>Material</dt><dd>{config.thickness} mm GS <span className="spec-color" style={{ background: config.tint.color }} title={materialLabel(config.tint, config.transparency)} /></dd></div><div><dt>Body clearance</dt><dd>{config.headroom} <small>mm</small></dd></div></dl><div className="summary-actions"><button className="button button-dark summary-export" onClick={onExportJson} aria-label="Export protector configuration as JSON"><ArrowDownToLine size={15} />JSON</button><button className="button button-orange summary-export" onClick={onExportSvg} aria-label="Export protector sheets as SVG"><ArrowDownToLine size={15} />SVG sheets</button></div></section>
  </div><aside className="control-panel accordion-control-panel" aria-label="Synth protector controls">
    <div className="panel-heading"><h2>Your synth protector</h2><span className="micro-label">01—05</span></div>
    <p className="config-intro">Open a section to fine-tune your protector.</p>
    <ConfigSection number="01" title="Your instrument" summary={`${config.width} × ${config.depth} × ${config.height} mm`} defaultOpen><p className="control-note stand-intro">A floating sheet above your synth, with slotted feet that locate against its edges.</p><Dimension label="Synth width" field="width" config={config} onChange={onChange} /><Dimension label="Synth depth" field="depth" config={config} onChange={onChange} /><Dimension label="Body height" field="height" config={config} onChange={onChange} /><p className="control-note">Measure to the flat top edge where the feet will rest, excluding pots and switches. This first option assumes a rectangular body with level, clear side edges.</p></ConfigSection>
    <ConfigSection number="02" title="Cover & clearance" summary={`${config.headroom} mm above body · ${config.overhang} mm overhang`} defaultOpen><Dimension label="Clearance above body" field="headroom" config={config} onChange={onChange} /><div className="preset-row"><span>Quick set</span>{[25, 35, 50, 75].map(headroom => <button key={headroom} className={headroom === config.headroom ? "preset-active" : ""} aria-pressed={headroom === config.headroom} onClick={() => onChange({ headroom })}>{headroom} mm</button>)}</div><p className="control-note">Body top to sheet underside. Include your tallest pot or switch plus extra space. Preview knobs are illustrative, 12 mm high.</p><Dimension label="Overhang on each edge" field="overhang" config={config} onChange={onChange} /><p className="control-note">Top sheet: {protector.dimensions.width} × {protector.dimensions.depth} mm. Overhang grows the sheet equally around the synth.</p></ConfigSection>
    <ConfigSection number="03" title="Feet & edge fit" summary={`${protector.footCount} feet · ${config.allSides ? "All four edges" : "Left & right"}`}>
      <div className="inline-field"><label htmlFor="protector-all-sides">Feet on all four edges</label><button id="protector-all-sides" role="switch" aria-checked={config.allSides} aria-label="Feet on all four edges" className={`toggle ${config.allSides ? "toggle-on" : ""}`} onClick={() => onChange({ allSides: !config.allSides })}><span /></button></div>
      <p className="control-note">{config.allSides ? "Support the front and rear as well as the left and right. Check that every edge has a flat contact area, clear of keys and connectors." : "Two end feet on the left and right edges. Add front and rear support for a cover that locates on all four sides."}</p>
      <Dimension label="Extra feet per left / right edge" field="sideExtraFeet" config={config} onChange={onChange} unit="feet" />
      {config.allSides && <Dimension label="Extra feet per front / rear edge" field="endExtraFeet" config={config} onChange={onChange} unit="feet" />}
      <p className="control-note">Intermediate feet are evenly spaced between the two end feet on each edge. Counts are limited to leave material between the slots.</p>
      <Dimension label="End feet from corners" field="footInset" config={config} onChange={onChange} />
      <Dimension label="Gap at synth sides" field="edgeGap" config={config} onChange={onChange} step={0.1} />
      <p className="control-note">Each foot rests on {protector.contactWidth.toFixed(1)} mm of the body edge, with a 12 mm lip down the outside. Zero gap meets the measured sides exactly. Corner inset grows when needed to keep adjacent feet and locking strips apart. Allow for protective pads in your measurements.</p>
    </ConfigSection>
    <ConfigSection number="04" title="Locking strips" summary={config.lockingStrips ? `${protector.stripCount} strips · Raised tabs` : "Off · Flush tabs"}>
      <div className="inline-field"><label htmlFor="protector-locking-strips">Through-tabs & locking strips</label><button id="protector-locking-strips" role="switch" aria-checked={config.lockingStrips} aria-label="Through-tabs & locking strips" className={`toggle ${config.lockingStrips ? "toggle-on" : ""}`} onClick={() => onChange({ lockingStrips: !config.lockingStrips })}><span /></button></div>
      <p className="control-note">{config.lockingStrips ? `Feet extend ${protector.retention.protrusion.toFixed(1)} mm above the cover. One strip slides through every foot on each supported edge, preventing the feet from dropping out.` : "Extend the foot tabs above the sheet and add a pass-through hole for a retaining strip along each supported edge."}</p>
      {config.lockingStrips && <><p className="control-note">Lower the cover, then thread each strip narrow end first through the aligned holes. The wider head stops insertion at the first foot. Pull the strips out before taking the cover apart.</p><p className="control-note">The strips remain removable and can slide back out. Test the joint fit and retention before lifting the cover assembly.</p></>}
    </ConfigSection>
    <ConfigSection number="05" title="Material & construction" summary={`${materialLabel(config.tint, config.transparency)} · ${config.thickness} mm acrylic`}><ColorChooser tint={config.tint} onChange={tint => onChange({ tint })} label="Protector acrylic color" /><TransparencyChooser value={config.transparency} onChange={transparency => onChange({ transparency })} /><MaterialPreviewNote /><Dimension label="Sheet thickness" field="thickness" config={config} onChange={onChange} step={0.1} /><Dimension label="Slot clearance" field="clearance" config={config} onChange={onChange} step={0.05} /><p className="control-note">{protector.footCount} {protector.slotLength.toFixed(2)} × {protector.slotWidth.toFixed(2)} mm slots receive the foot tabs. {protector.parts.length} parts, all the same material. No screws or glue.</p><p className="stand-prototype-note">First prototype · no tested load or impact rating. Check fit, contact surfaces and sheet flex before use. Do not stack equipment on the cover. Cut a joint sample and review internal corners with your cutter.</p></ConfigSection>
  </aside></div>;
}
