"use client";
import { lazy, Suspense, useId, useState, type CSSProperties } from "react";
import { ArrowDownToLine, Box, Check, Layers2, Maximize, Minimize, RotateCcw } from "lucide-react";
import { ConfigSection } from "./config-section";
import { SheetMaterialControls, SheetMaterialSwatches } from "./sheet-material-controls";
import { allSheetMaterials, sheetMaterial, sheetThicknessLabel } from "@/lib/sheet-materials";
import { FabricationButton } from "./fabrication-button";
import { myndSource, speakerLimits, speakerSheetLayout, type Speaker, type SpeakerConfiguration } from "@/lib/speaker";
import { standPathData } from "@/lib/synth-stand";
import type { SpeakerView } from "./speaker-preview";
const SpeakerPreview=lazy(()=>import("./speaker-preview").then(module=>({default:module.SpeakerPreview})));
function Slider({label,value,min,max,step=1,onChange}: {label:string;value:number;min:number;max:number;step?:number;onChange:(value:number)=>void}) {
  const id=useId();
  return <div className="range-field"><div className="field-heading"><label htmlFor={id}>{label}</label><div className="number-field"><input type="number" aria-label={`${label} in mm`} min={min} max={max} step={step} value={Number(value.toFixed(2))} onChange={event=>{const next=event.currentTarget.valueAsNumber;if(Number.isFinite(next))onChange(Math.max(min,Math.min(max,next)));}} /><span>mm</span></div></div><input id={id} className="range-input" type="range" min={min} max={max} step={step} value={value} style={{"--range-progress":`${(value-min)/(max-min)*100}%`} as CSSProperties} onChange={event=>onChange(event.currentTarget.valueAsNumber)} /><div className="range-labels"><span>{min} mm</span><span>{max} mm</span></div></div>;
}
function CuttingLayout({speaker}: {speaker:Speaker}) {
  const layout=speakerSheetLayout(speaker);
  return <div className="stand-cutting-layout"><svg viewBox={`0 0 ${layout.width} ${layout.height}`} role="img" aria-label="Speaker cutting layout: 7 acrylic sheets">{layout.parts.map(({part,x,y})=><g key={part.id} data-part={part.id} transform={`translate(${x} ${y})`}><title>{part.label} · {part.width.toFixed(1)} × {part.height.toFixed(1)} mm</title><path d={standPathData(part.polygons)} fill={sheetMaterial(speaker.config,part.id).tint.color} fillOpacity={sheetMaterial(speaker.config,part.id).transparency === "opaque" ? 1 : 0.4} stroke="currentColor" strokeWidth={0.5} vectorEffect="non-scaling-stroke" fillRule="evenodd" /></g>)}</svg><p>7 sheets · {layout.width.toFixed(0)} × {layout.height.toFixed(0)} mm · Prototype · verify donor fit</p></div>;
}
type Props={speaker:Speaker;dark:boolean;onChange:(patch:Partial<SpeakerConfiguration>)=>void;onExportJson:()=>void;onExportSvg:()=>void;onOpenFabrication:()=>void};
export function SpeakerDesigner({speaker,dark,onChange,onExportJson,onExportSvg,onOpenFabrication}:Props) {
  const config=speaker.config;
  const [view,setView]=useState<SpeakerView>("perspective"),[layout,setLayout]=useState(false),[exploded,setExploded]=useState(false),[expanded,setExpanded]=useState(false),[hardware,setHardware]=useState(true),[resetKey,setResetKey]=useState(0);
  const dimension=(label:string,field:keyof typeof speakerLimits,step=1)=><Slider label={label} value={config[field]} {...speakerLimits[field]} step={step} onChange={value=>onChange(field === "thickness" ? allSheetMaterials(config,{thickness:value}) : {[field]:value})} />;
  return <div className="configurator-grid speaker-designer"><div className="preview-column">
    <section className={`preview-stage ${expanded ? "preview-expanded" : ""}`} aria-label="Speaker preview" onKeyDown={event=>{if(event.key === "Escape")setExpanded(false);}}>
      <div className="stage-topline"><div className="model-label"><span className="status-dot" /><span>MYND / RECASED</span><span className="model-label-separator">/</span><span>7 SHEETS</span></div><span className="stage-material">GS—{sheetThicknessLabel(config,speaker.parts)} <span>•</span> ACRYLIC</span></div>
      <div className="stage-watermark" aria-hidden="true">M-508</div>
      <div className="canvas-wrap">{layout ? <CuttingLayout speaker={speaker} /> : <Suspense fallback={<div className="preview-fallback" role="status">Building your speaker…</div>}><SpeakerPreview speaker={speaker} dark={dark} exploded={exploded} hardware={hardware} view={view} resetKey={resetKey} /></Suspense>}</div>
      <div className="stage-side-tools"><button className={`icon-button ${exploded && !layout ? "tool-active" : ""}`} aria-label="Exploded speaker view" aria-pressed={exploded && !layout} title="Exploded view" onClick={()=>{setLayout(false);setExploded(!exploded);}}><Layers2 size={18} /></button><span /><button className="icon-button" aria-label="Reset speaker camera" onClick={()=>{setLayout(false);setView("perspective");setResetKey(key=>key+1);}}><RotateCcw size={16} /></button><button className="icon-button" aria-label={expanded ? "Exit expanded speaker preview" : "Expand speaker preview"} onClick={()=>setExpanded(!expanded)}>{expanded ? <Minimize size={16} /> : <Maximize size={16} />}</button></div>
      <div className="stage-bottom"><div className="view-control" role="group" aria-label="Speaker view">{(["perspective","front","rear"] as const).map(option=><button key={option} className={!layout && view === option ? "view-active" : ""} aria-pressed={!layout && view === option} onClick={()=>{setLayout(false);setView(option);}}>{option === "perspective" && <Box size={13} />}{option === "perspective" ? "Perspective" : option === "front" ? "Front" : "Rear"}</button>)}<button className={layout ? "view-active" : ""} aria-pressed={layout} onClick={()=>setLayout(true)}>Cutting layout</button></div><span className="stage-hint">{layout ? "Full-size SVG available below" : "Drag to orbit · Scroll to zoom"}</span></div>
      <div className="stage-caption"><span><Check size={12} />{layout ? "Baffle + sealed shell + separate dot grille" : exploded ? "Seven sheets · original MYND hardware" : "MYND drivers & electronics · acrylic enclosure"}</span><span>PROTOTYPE · MM</span></div>
    </section>
    <section className="summary-panel" aria-label="Speaker specification"><div className="summary-title"><span className="micro-label">SPEAKER SPECIFICATION</span><h2>MYND <span>/</span> Acrylic</h2></div><dl className="spec-list"><div><dt>Enclosure W × H × D</dt><dd>{config.width} × {config.height} × {speaker.totalDepth} <small>mm</small></dd></div><div><dt>Gross chamber</dt><dd>{speaker.grossVolumeLitres.toFixed(2)} <small>L · before hardware</small></dd></div><div><dt>Dot grille</dt><dd>{speaker.dots.length} holes · {speaker.openArea.toFixed(0)}% open</dd></div><div><dt>Material</dt><dd><SheetMaterialSwatches config={config} parts={speaker.parts} /></dd></div></dl><div className="summary-actions"><FabricationButton onClick={onOpenFabrication} /><button className="button button-dark summary-export" aria-label="Export speaker design JSON" onClick={onExportJson}><ArrowDownToLine size={15} />Design JSON</button><button className="button button-orange summary-export" aria-label="Export speaker sheets as SVG" onClick={onExportSvg}><ArrowDownToLine size={15} />SVG sheets</button></div></section>
  </div><aside className="control-panel accordion-control-panel" aria-label="Speaker controls"><div className="panel-heading"><h2>A new case for MYND</h2><span className="micro-label">01—05</span></div><p className="config-intro">Teufel’s open hardware. Your acrylic enclosure.</p>
    <ConfigSection number="01" title="Enclosure" summary={`${config.width} × ${config.height} × ${config.depth} mm body`} defaultOpen>{dimension("Speaker width","width")}{dimension("Speaker height","height")}{dimension("Body depth","depth")}<p className="control-note">The grille adds {(speaker.totalDepth-config.depth).toFixed(1)} mm to the body depth. Driver centres stay fixed to the MYND layout as the case grows. Internal volume is a gross estimate; matching the original tuning needs a prototype.</p></ConfigSection>
    <ConfigSection number="02" title="Dot grille" summary={`Ø ${config.dotDiameter} · ${config.dotPitch} mm pitch · ${config.staggered ? "Staggered" : "Aligned"}`} defaultOpen>{dimension("Dot diameter","dotDiameter",0.1)}{dimension("Dot spacing","dotPitch",0.1)}{dimension("Grille border","grilleBorder")}{dimension("Grille standoff","grilleGap")}<div className="inline-field"><label htmlFor="speaker-stagger">Staggered dots</label><button id="speaker-stagger" className={`toggle ${config.staggered ? "toggle-on" : ""}`} role="switch" aria-checked={config.staggered} aria-label="Staggered dots" onClick={()=>onChange({staggered:!config.staggered})}><span /></button></div><p className="control-note">{speaker.openArea.toFixed(1)}% of the pattern field is open. Spacing preserves at least 2 mm between holes. The perforated cover sits in front of the sealed baffle; allow clearance for radiator movement.</p></ConfigSection>
    <ConfigSection number="03" title="Acrylic sheets" summary={`${sheetThicknessLabel(config,speaker.parts)} mm GS · 7 sheets`}><SheetMaterialControls config={config} parts={speaker.parts} limits={speakerLimits.thickness} label="Speaker acrylic color" onChange={onChange} />{dimension(config.individualSheetMaterials ? "Apply thickness to all sheets" : "Sheet thickness","thickness",0.1)}<p className="control-note">Bonded butt joints form the chamber. A gasketed rear on corner tie rods keeps the original electronics accessible.</p></ConfigSection>
    <ConfigSection number="04" title="MYND hardware" summary="1 woofer · 2 tweeters · 2 passive radiators"><div className="inline-field"><label htmlFor="speaker-hardware">Show donor hardware</label><button id="speaker-hardware" className={`toggle ${hardware ? "toggle-on" : ""}`} role="switch" aria-checked={hardware} aria-label="Show donor hardware" onClick={()=>setHardware(!hardware)}><span /></button></div><p className="control-note">Reuse the 90 mm woofer, two 20 mm tweeters, both passive radiators and the original electronics, battery and wiring. The nine PCB assemblies use the released layouts and component models, alongside the original radiator frames, port housing and control parts. Drivers, battery and cable routes are reconstructed. Verify placement and clearances against your donor.</p><div className="stand-parts">{[["Main board","75 × 136 mm"],["Amplifier","90.5 × 57.5 mm"],["Bluetooth board","55 × 41 mm"],["UI board","116 × 26 mm"]].map(([label,size])=><div key={label}><strong>1×</strong><span>{label}<small>{size} · source PCB assembly</small></span></div>)}</div><p className="control-note"><a href={myndSource} target="_blank" rel="noreferrer">Teufel MYND hardware ↗</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>. Flat-sheet adaptation; no verified acoustic or weatherproof rating.</p></ConfigSection>
    <ConfigSection number="05" title="Service openings & parts" summary="Side ports · top controls · removable rear"><p className="control-note">Mounting holes follow the PCB and control-cover supports on the top, base, rear and baffle. The side opening follows the original housing’s access profile (41 × 20.1 mm), with four aligned screw holes. It stays fixed to fit the donor. The top has three Ø18 mm button cutouts and one 38 × 18 mm volume-rocker cutout, aligned to the original controls. The rubber backing stays below the sheet; thicker acrylic recesses the buttons further. Verify button travel and seal the assemblies. Simplified baffle seats also need retainers; see Build notes before cutting.</p><div className="stand-parts">{speaker.parts.map(part=><div key={part.id}><strong>1×</strong><span>{part.label}<small>{part.width.toFixed(1)} × {part.height.toFixed(1)} × {part.thickness} mm</small></span></div>)}</div></ConfigSection>
  </aside></div>;
}
