"use client";
import { lazy, Suspense, useId, useState, type CSSProperties } from "react";
import { ArrowDownToLine, Box, Check, Layers2, Maximize, Minimize, RotateCcw, SlidersHorizontal } from "lucide-react";
import { acrylicTints } from "@/lib/configurator";
import { standLimits, standPathData, standSheetLayout, type StandConfiguration, type SynthStand } from "@/lib/synth-stand";
import type { StandView } from "@/components/stand-preview";
const StandPreview = lazy(() => import("@/components/stand-preview").then(module => ({ default: module.StandPreview })));

function Dimension({ label, field, config, onChange, unit = "mm", step = 1 }: { label: string; field: keyof typeof standLimits; config: StandConfiguration; onChange: (patch: Partial<StandConfiguration>) => void; unit?: string; step?: number }) {
  const id = useId(), value = config[field], { min, max } = standLimits[field];
  const [draft, setDraft] = useState<string | null>(null);
  function commit() {
    if (draft?.trim() && Number.isFinite(Number(draft))) onChange({ [field]: Math.max(min, Math.min(max, Number(draft))) });
    setDraft(null);
  }
  return <div className="range-field"><div className="field-heading"><label htmlFor={id}>{label}</label><div className="number-field"><input aria-label={`${label} in ${unit}`} type="number" min={min} max={max} step={step} value={draft ?? value} onFocus={() => setDraft(String(value))} onChange={event => { setDraft(event.target.value); const next = Number(event.target.value); if (event.target.value && Number.isFinite(next) && next >= min && next <= max) onChange({ [field]: next }); }} onBlur={commit} onKeyDown={event => { if (event.key === "Enter") event.currentTarget.blur(); }} /><span>{unit}</span></div></div><input id={id} className="range-input" type="range" min={min} max={max} step={step} value={value} style={{ "--range-progress": `${(value - min) / (max - min) * 100}%` } as CSSProperties} onChange={event => onChange({ [field]: event.currentTarget.valueAsNumber })} /><div className="range-labels"><span>{min} {unit}</span><span>{max} {unit}</span></div></div>;
}
function CuttingLayout({ stand }: { stand: SynthStand }) {
  const layout = standSheetLayout(stand);
  return <div className="stand-cutting-layout"><svg viewBox={`0 0 ${layout.width} ${layout.height}`} role="img" aria-label={`Cutting layout: ${stand.ribCount} support ribs and 3 cross braces`}>
    {layout.parts.map(({ part, x, y }) => <g key={part.id} transform={`translate(${x} ${y})`}><title>{part.label}: {part.width.toFixed(1)} × {part.height.toFixed(1)} mm</title><path d={standPathData(part.polygons)} fill={stand.config.tint.color} fillOpacity={0.4} stroke="currentColor" strokeWidth={1} vectorEffect="non-scaling-stroke" fillRule="evenodd" /></g>)}
  </svg><p>All {stand.parts.length} parts · {layout.width.toFixed(0)} × {layout.height.toFixed(0)} mm layout · arrange to fit your stock sheet</p></div>;
}
type Props = { stand: SynthStand; dark: boolean; onChange: (patch: Partial<StandConfiguration>) => void; onExportJson: () => void; onExportSvg: () => void };
export function StandDesigner({ stand, dark, onChange, onExportJson, onExportSvg }: Props) {
  const config = stand.config;
  const [view, setView] = useState<StandView>("perspective");
  const [layout, setLayout] = useState(false), [exploded, setExploded] = useState(false), [instrument, setInstrument] = useState(false);
  const [expanded, setExpanded] = useState(false), [resetKey, setResetKey] = useState(0);
  return <div className="configurator-grid stand-designer"><div className="preview-column">
    <section className={`preview-stage ${expanded ? "preview-expanded" : ""}`} aria-label="Synth stand preview" onKeyDown={event => { if (event.key === "Escape") setExpanded(false); }}>
      <div className="stage-topline"><div className="model-label"><span className="status-dot" /><span>SYNTH STAND</span><span className="model-label-separator">/</span><span>{config.angle}° · {stand.parts.length} PARTS</span></div><span className="stage-material">GS—{config.thickness} <span>•</span> {config.tint.label.toUpperCase()}</span></div>
      <div className="stage-watermark" aria-hidden="true">S—508</div>
      <div className="canvas-wrap">{layout ? <CuttingLayout stand={stand} /> : <Suspense fallback={<div className="preview-fallback" role="status">Preparing your stand…</div>}><StandPreview stand={stand} dark={dark} exploded={exploded} instrument={instrument} view={view} resetKey={resetKey} /></Suspense>}</div>
      <div className="stage-side-tools"><button className={`icon-button ${exploded && !layout ? "tool-active" : ""}`} aria-label="Exploded stand view" aria-pressed={exploded && !layout} title="Exploded view" onClick={() => { setLayout(false); setExploded(!exploded); }}><Layers2 size={18} /></button><button className={`icon-button ${instrument && !layout ? "tool-active" : ""}`} aria-label="Show synth envelope" aria-pressed={instrument && !layout} title="Show synth envelope" onClick={() => { setLayout(false); setInstrument(!instrument); }}><SlidersHorizontal size={18} /></button><span /><button className="icon-button" aria-label="Reset stand camera" title="Reset camera" onClick={() => { setView("perspective"); setLayout(false); setResetKey(key => key + 1); }}><RotateCcw size={16} /></button><button className="icon-button" aria-label={expanded ? "Exit expanded stand preview" : "Expand stand preview"} title="Expand preview" onClick={() => setExpanded(!expanded)}>{expanded ? <Minimize size={16} /> : <Maximize size={16} />}</button></div>
      <div className="stage-bottom"><div className="view-control" role="group" aria-label="Stand view">{(["perspective", "side", "top"] as const).map(option => <button key={option} className={!layout && view === option ? "view-active" : ""} aria-pressed={!layout && view === option} onClick={() => { setLayout(false); setView(option); }}>{option === "perspective" && <Box size={13} />}{option === "perspective" ? "Perspective" : option === "side" ? "Side" : "Top"}</button>)}<button className={layout ? "view-active" : ""} aria-pressed={layout} onClick={() => setLayout(true)}>Cutting layout</button></div><span className="stage-hint">{layout ? "Full-size SVG available below" : "Drag to orbit · Scroll to zoom"}</span></div>
      <div className="stage-caption"><span><Check size={12} />{layout ? "Shared preview & export geometry" : instrument ? "Synth envelope · check actual feet & controls" : exploded ? "Lower ribs onto the three cross braces" : "Solid ribs · three interlocking cross braces"}</span><span>PROTOTYPE · MM</span></div>
    </section>
    <section className="summary-panel" aria-label="Stand specification"><div className="summary-title"><span className="micro-label">STAND SPECIFICATION</span><h2>S508 <span>/</span> {config.angle}°</h2></div><dl className="spec-list"><div><dt>Footprint</dt><dd>{stand.dimensions.width.toFixed(0)} × {stand.dimensions.depth.toFixed(0)} <small>mm</small></dd></div><div><dt>Construction</dt><dd>{stand.ribCount} ribs + 3 braces</dd></div><div><dt>Material</dt><dd>{config.thickness} mm GS <span className="spec-color" style={{ background: config.tint.color }} /></dd></div><div><dt>Stand height</dt><dd>{stand.dimensions.height.toFixed(0)} <small>mm</small></dd></div></dl><div className="summary-actions"><button className="button button-dark summary-export" onClick={onExportJson} aria-label="Export stand configuration as JSON"><ArrowDownToLine size={15} />JSON</button><button className="button button-orange summary-export" onClick={onExportSvg} aria-label="Export stand sheets as SVG"><ArrowDownToLine size={15} />SVG sheets</button></div></section>
  </div><aside className="control-panel" aria-label="Synth stand controls">
    <div className="panel-heading"><h2>Your synth stand</h2><span className="micro-label">01—04</span></div>
    <section className="control-section"><div className="section-heading"><span className="section-number">01</span><h3>Your instrument</h3><span className="section-detail">MILLIMETRES</span></div><p className="control-note stand-intro">Measure the full body of your synth. We’ll shape the support and space the ribs to suit.</p><Dimension label="Synth width" field="width" config={config} onChange={onChange} /><Dimension label="Synth depth" field="depth" config={config} onChange={onChange} /><Dimension label="Synth height" field="height" config={config} onChange={onChange} /><p className="control-note">Height extends the front footprint when tilted. The optional synth envelope shows a rectangular body; check feet, front controls and connectors on your instrument.</p></section>
    <section className="control-section"><div className="section-heading"><span className="section-number">02</span><h3>Playing angle</h3></div><Dimension label="Tilt angle" field="angle" config={config} onChange={onChange} unit="°" /><div className="preset-row"><span>Quick set</span>{[0, 15, 25, 35, 45].map(angle => <button key={angle} className={angle === config.angle ? "preset-active" : ""} aria-pressed={angle === config.angle} onClick={() => onChange({ angle })}>{angle}°</button>)}</div><p className="control-note">{stand.frontHeight.toFixed(0)} mm front support height · {stand.stopHeight.toFixed(0)} mm integral front stops. Extended feet reach beyond the tilted instrument.</p></section>
    <section className="control-section"><div className="section-heading"><span className="section-number">03</span><h3>Material & fit</h3><span className="section-detail">GS ACRYLIC</span></div><div className="field-heading"><span>Acrylic tint</span><span className="field-note">{config.tint.label}</span></div><div className="swatch-list" aria-label="Stand acrylic tint">{acrylicTints.map(tint => <button key={tint.id} className={`tint-swatch ${tint.id === config.tint.id ? "tint-swatch-active" : ""}`} style={{ "--swatch": tint.color } as CSSProperties} aria-label={`${tint.label} stand acrylic`} aria-pressed={tint.id === config.tint.id} onClick={() => onChange({ tint })}><span className="swatch-surface">{tint.id === config.tint.id && <Check size={18} />}</span><span className="swatch-caption">{tint.id === "orange" ? "Orange" : tint.id === "green" ? "Sea glass" : tint.label}</span></button>)}</div><Dimension label="Sheet thickness" field="thickness" config={config} onChange={onChange} step={0.1} /><Dimension label="Slot clearance" field="clearance" config={config} onChange={onChange} step={0.05} /><p className="control-note">{stand.slotWidth.toFixed(2)} mm slots, including clearance. Enter measured sheet thickness. Cut a fit sample first; apply laser kerf compensation in your cutting software.</p></section>
    <section className="control-section"><div className="section-heading"><span className="section-number">04</span><h3>Your parts</h3><span className="section-detail">AUTO</span></div><div className="stand-parts"><div><strong>{stand.ribCount}×</strong><span>Solid support ribs<small>{stand.dimensions.depth.toFixed(1)} × {stand.dimensions.height.toFixed(1)} mm</small></span></div><div><strong>3×</strong><span>Slotted cross braces<small>{stand.braceWidth.toFixed(1)} × {stand.braceHeight.toFixed(1)} mm</small></span></div></div><p className="control-note">Ribs spaced {stand.supportSpacing.toFixed(0)} mm apart. Auto adds ribs to keep spans at or below 220 mm. All {stand.parts.length} pieces use the same sheet thickness.</p><div className="hardware-note"><span className="hardware-dot" />Acrylic only <span>Slot together · no glue</span></div><p className="control-note">Stand the braces slots-up, then lower the ribs slots-down. Front stops are part of each rib. Remove the synth before moving the stand; the joints lift apart.</p><p className="stand-prototype-note">Prototype design · no load rating. Rib count is a spacing rule, not a strength calculation. Test fit, flex, racking, surface grip and tipping before use.</p></section>
  </aside></div>;
}
