"use client";
import { lazy, Suspense, useId, useState, type CSSProperties } from "react";
import { ArrowDownToLine, Box, Check, Layers2, Maximize, Minimize, Minus, Plus, RotateCcw, SlidersHorizontal } from "lucide-react";
import { StandObjectControls } from "@/components/stand-object-controls";
import type { StandObject } from "@/lib/stand-object";
import { ConfigSection } from "@/components/config-section";
import { materialLabel } from "@/lib/acrylic-material";
import { ColorChooser, TransparencyChooser, MaterialPreviewNote } from "@/components/material-controls";
import { standLimits, standPathData, standSheetLayout, type StandConfiguration, type SynthStand } from "@/lib/synth-stand";
import type { StandView } from "@/components/stand-preview";
const StandPreview = lazy(() => import("@/components/stand-preview").then(module => ({ default: module.StandPreview })));

function Dimension({ label, field, config, onChange, unit = "mm", step = 1 }: { label: string; field: keyof typeof standLimits; config: StandConfiguration; onChange: (patch: Partial<StandConfiguration>) => void; unit?: string; step?: number }) {
  const id = useId(), value = config[field], { min, max } = standLimits[field];
  const [draft, setDraft] = useState<string | null>(null);
  function commit() {
    if (draft?.trim() && Number.isFinite(Number(draft))) onChange({ [field]: Math.max(min, Math.min(max, Number(draft))) });
    setDraft(null);
  }
  return <div className="range-field"><div className="field-heading"><label htmlFor={id}>{label}</label><div className="number-field"><input aria-label={`${label} in ${unit}`} type="number" min={min} max={max} step={step} value={draft ?? value} onFocus={() => setDraft(String(value))} onChange={event => { setDraft(event.target.value); const next = Number(event.target.value); if (event.target.value && Number.isFinite(next) && next >= min && next <= max) onChange({ [field]: next }); }} onBlur={commit} onKeyDown={event => { if (event.key === "Enter") event.currentTarget.blur(); }} /><span>{unit}</span></div></div><input id={id} className="range-input" type="range" min={min} max={max} step={step} value={value} style={{ "--range-progress": `${(value - min) / (max - min) * 100}%` } as CSSProperties} onChange={event => onChange({ [field]: event.currentTarget.valueAsNumber })} /><div className="range-labels"><span>{min} {unit}</span><span>{max} {unit}</span></div></div>;
}
function CuttingLayout({ stand }: { stand: SynthStand }) {
  const layout = standSheetLayout(stand);
  return <div className="stand-cutting-layout"><svg viewBox={`0 0 ${layout.width} ${layout.height}`} role="img" aria-label={`Cutting layout: ${stand.ribCount} support ribs and ${stand.braceCount} cross braces`}>
    {layout.parts.map(({ part, x, y }) => <g key={part.id} transform={`translate(${x} ${y})`}><title>{part.label}: {part.width.toFixed(1)} × {part.height.toFixed(1)} mm</title><path d={standPathData(part.polygons)} fill={stand.config.tint.color} fillOpacity={0.4} stroke="currentColor" strokeWidth={1} vectorEffect="non-scaling-stroke" fillRule="evenodd" /></g>)}
  </svg><p>All {stand.parts.length} parts · {layout.width.toFixed(0)} × {layout.height.toFixed(0)} mm layout · arrange to fit your stock sheet</p></div>;
}
type Props = { busy?: boolean; object?: StandObject; objectError?: string; stand: SynthStand; dark: boolean; onChange: (patch: Partial<StandConfiguration>) => void; onExportJson: () => void; onExportSvg: () => void };
export function StandDesigner({ stand, object, objectError, busy, dark, onChange, onExportJson, onExportSvg }: Props) {
  const config = stand.config;
  const rib = stand.parts[0];
  const [view, setView] = useState<StandView>("perspective");
  const [layout, setLayout] = useState(false), [exploded, setExploded] = useState(false), [instrument, setInstrument] = useState(!!object);
  const [expanded, setExpanded] = useState(false), [resetKey, setResetKey] = useState(0);
  return <div className="configurator-grid stand-designer"><div className="preview-column">
    <section className={`preview-stage ${expanded ? "preview-expanded" : ""}`} aria-label="Synth stand preview" onKeyDown={event => { if (event.key === "Escape") setExpanded(false); }}>
      <div className="stage-topline"><div className="model-label"><span className="status-dot" /><span>{config.advancedMode ? "DIAGONAL STAND" : "SYNTH STAND"}</span><span className="model-label-separator">/</span><span>{config.angle}° · {stand.parts.length} PARTS</span></div><span className="stage-material">GS—{config.thickness} <span>•</span> {materialLabel(config.tint, config.transparency).toUpperCase()}</span></div>
      <div className="stage-watermark" aria-hidden="true">S-508</div>
      <div className="canvas-wrap">{busy ? <div className="preview-fallback" role="status">Fitting the stand to your model…</div> : objectError ? <div className="preview-fallback" role="status">Adjust the model settings to generate a fitted stand.</div> : layout ? <CuttingLayout stand={stand} /> : <Suspense fallback={<div className="preview-fallback" role="status">Preparing your stand…</div>}><StandPreview stand={stand} dark={dark} exploded={exploded} instrument={instrument} view={view} resetKey={resetKey} /></Suspense>}</div>
      <div className="stage-side-tools"><button className={`icon-button ${exploded && !layout ? "tool-active" : ""}`} aria-label="Exploded stand view" aria-pressed={exploded && !layout} title="Exploded view" onClick={() => { setLayout(false); setExploded(!exploded); }}><Layers2 size={18} /></button><button className={`icon-button ${instrument && !layout ? "tool-active" : ""}`} aria-label={object ? "Show uploaded object" : "Show synth envelope"} aria-pressed={instrument && !layout} title={object ? "Show uploaded object" : "Show synth envelope"} onClick={() => { setLayout(false); setInstrument(!instrument); }}><SlidersHorizontal size={18} /></button><span /><button className="icon-button" aria-label="Reset stand camera" title="Reset camera" onClick={() => { setView("perspective"); setLayout(false); setResetKey(key => key + 1); }}><RotateCcw size={16} /></button><button className="icon-button" aria-label={expanded ? "Exit expanded stand preview" : "Expand stand preview"} title="Expand preview" onClick={() => setExpanded(!expanded)}>{expanded ? <Minimize size={16} /> : <Maximize size={16} />}</button></div>
      <div className="stage-bottom"><div className="view-control" role="group" aria-label="Stand view">{(["perspective", "side", "top"] as const).map(option => <button key={option} className={!layout && view === option ? "view-active" : ""} aria-pressed={!layout && view === option} onClick={() => { setLayout(false); setView(option); }}>{option === "perspective" && <Box size={13} />}{option === "perspective" ? "Perspective" : option === "side" ? "Side" : "Top"}</button>)}<button className={layout ? "view-active" : ""} aria-pressed={layout} onClick={() => setLayout(true)}>Cutting layout</button></div><span className="stage-hint">{layout ? "Full-size SVG available below" : "Drag to orbit · Scroll to zoom"}</span></div>
      <div className="stage-caption"><span><Check size={12} />{layout ? "Shared preview & export geometry" : instrument ? (object ? "Model contour fit · verify against the real object" : "Synth envelope · check actual feet & controls") : exploded ? (config.advancedMode ? "Lower family A into family B · all joints at 90°" : "Lower ribs onto the three cross braces") : config.advancedMode ? "Crossed main supports · 90° half-lap slots" : "Solid ribs · three interlocking cross braces"}</span><span>PROTOTYPE · MM</span></div>
    </section>
    <section className="summary-panel" aria-label="Stand specification"><div className="summary-title"><span className="micro-label">STAND SPECIFICATION</span><h2>S508 <span>/</span> {config.angle}°</h2></div>{busy || objectError ? <p className="control-note" role="status">{busy ? "Fitting your model…" : "Resolve the model settings before exporting."}</p> : <dl className="spec-list"><div><dt>Footprint</dt><dd>{stand.dimensions.width.toFixed(0)} × {stand.dimensions.depth.toFixed(0)} <small>mm</small></dd></div><div><dt>Construction</dt><dd>{stand.ribCount} ribs + {stand.braceCount} braces</dd></div><div><dt>Material</dt><dd>{config.thickness} mm GS <span className="spec-color" style={{ background: config.tint.color }} title={materialLabel(config.tint, config.transparency)} /></dd></div><div><dt>Stand height</dt><dd>{stand.dimensions.height.toFixed(0)} <small>mm</small></dd></div></dl>}<div className="summary-actions"><button className="button button-dark summary-export" disabled={!!objectError || busy} onClick={onExportJson} aria-label="Export stand configuration as JSON"><ArrowDownToLine size={15} />JSON</button><button className="button button-orange summary-export" disabled={!!objectError || busy} onClick={onExportSvg} aria-label="Export stand sheets as SVG"><ArrowDownToLine size={15} />SVG sheets</button></div></section>
  </div><aside className="control-panel accordion-control-panel" aria-label="Synth stand controls">
    <div className="panel-heading"><h2>Your synth stand</h2><span className="micro-label">01—05</span></div>
    <div className="stand-mode-control">
      <div className="view-control" role="group" aria-label="Stand construction mode">
        <button className={!config.advancedMode ? "view-active" : ""} aria-pressed={!config.advancedMode} onClick={() => onChange({ advancedMode: false })}>Standard</button>
        <button className={config.advancedMode ? "view-active" : ""} aria-pressed={config.advancedMode} onClick={() => onChange({ advancedMode: true })}>Advanced · diagonal</button>
      </div>
      <p className="control-note">{config.advancedMode ? "Full-height sheets cross in both diagonal directions. Four low braces reinforce the same two directions." : "Straight support ribs and three interlocking cross braces."}</p>
      {config.advancedMode && <p className="control-note" role="status">±45° in top view · every crossing stays at 90°. Main supports follow your playing tilt; braces stay below the synth.</p>}
    </div>
    <p className="config-intro">Open a section to fine-tune your stand.</p>
    <ConfigSection number="01" title="Your instrument" summary={busy ? "Fitting model…" : objectError ? "Check model settings" : `${config.width.toFixed(1)} × ${config.depth.toFixed(1)} × ${config.height.toFixed(1)} mm`} defaultOpen>
      <StandObjectControls model={object} error={objectError} onChange={object => { onChange({ object }); if (object) setInstrument(true); }} />
      {object ? !objectError && !busy && <p className="control-note" role="status">Model size · {config.width.toFixed(1)} W × {config.depth.toFixed(1)} D × {config.height.toFixed(1)} H mm. Confirm these dimensions match the real object.</p> : <><p className="control-note stand-intro">Or measure the full body of your synth. We’ll shape the support and space the ribs to suit.</p><Dimension label="Synth width" field="width" config={config} onChange={onChange} /><Dimension label="Synth depth" field="depth" config={config} onChange={onChange} /><Dimension label="Synth height" field="height" config={config} onChange={onChange} /><p className="control-note">Height sets the optional rectangular synth envelope; check feet, front controls and connectors on your instrument.</p></>}
    </ConfigSection>
    <ConfigSection number="02" title="Playing angle" summary={`${config.angle}° tilt · ${config.frontExtension ? `${config.frontExtensionLength} mm front extension` : "Compact footprint"}`}><div className="config-group"><Dimension label="Tilt angle" field="angle" config={config} onChange={onChange} unit="°" /><div className="preset-row"><span>Quick set</span>{[0, 15, 25, 35, 45].map(angle => <button key={angle} className={angle === config.angle ? "preset-active" : ""} aria-pressed={angle === config.angle} onClick={() => onChange({ angle })}>{angle}°</button>)}</div><p className="control-note">{object ? `${stand.frontHeight.toFixed(0)} mm minimum support height. The object and contact profiles rotate together.` : `${stand.frontHeight.toFixed(0)} mm front support height · ${stand.stopHeight.toFixed(0)} mm integral front stops. Front stops remain in both footprint options.`}</p>
      </div>
      <div className="config-group">
      <div className="inline-field"><label htmlFor="stand-front-extension">Front extension</label><button id="stand-front-extension" role="switch" aria-checked={config.frontExtension} aria-label="Front extension" aria-describedby="stand-front-extension-note" className={`toggle ${config.frontExtension ? "toggle-on" : ""}`} onClick={() => onChange({ frontExtension: !config.frontExtension })}><span>{config.frontExtension ? <Plus size={10} /> : <Minus size={10} />}</span></button></div>
      <p className="control-note" id="stand-front-extension-note">{config.frontExtension ? (object ? "Add a little more footprint ahead of the object. Length is measured horizontally." : "Add a little more footprint ahead of the front stops. Length is measured horizontally.") : (object ? "Compact footprint: one sheet thickness beyond the tilted model at each end." : "Compact footprint: the feet end beneath the front stops, with no extra toe.")}</p>
      {config.frontExtension && <Dimension label="Extension length" field="frontExtensionLength" config={config} onChange={onChange} />}
      </div>
    </ConfigSection>
    <ConfigSection number="03" title="Material & fit" summary={`${materialLabel(config.tint, config.transparency)} · ${config.thickness} mm acrylic${config.roundedEdges ? " · Rounded edges" : ""}`}><div className="config-group"><ColorChooser tint={config.tint} onChange={tint => onChange({ tint })} label="Stand acrylic color" /><TransparencyChooser value={config.transparency} onChange={transparency => onChange({ transparency })} /><MaterialPreviewNote /><Dimension label="Sheet thickness" field="thickness" config={config} onChange={onChange} step={0.1} /><Dimension label="Slot clearance" field="clearance" config={config} onChange={onChange} step={0.05} /><p className="control-note">{stand.slotWidth.toFixed(2)} mm slots, including clearance.{config.advancedMode ? " Every crossing is perpendicular, so the slot fit stays the same." : ""} Enter measured sheet thickness. Cut a fit sample first; apply laser kerf compensation in your cutting software.</p>
      </div>
      <div className="config-group">
      <div className="inline-field"><label htmlFor="stand-rounded-edges">Rounded edges</label><button id="stand-rounded-edges" role="switch" aria-checked={config.roundedEdges} aria-label="Rounded edges" aria-describedby="stand-rounded-edges-note" className={`toggle ${config.roundedEdges ? "toggle-on" : ""}`} onClick={() => onChange({ roundedEdges: !config.roundedEdges })}><span>{config.roundedEdges ? <Plus size={10} /> : <Minus size={10} />}</span></button></div>
      <p className="control-note" id="stand-rounded-edges-note">Round the outside corners of the ribs, front stops and braces. Joint slots and the synth contact angle stay unchanged. This shapes the flat cutting outline; sheet faces stay flat.</p>
      {config.roundedEdges && <><Dimension label="Corner radius" field="cornerRadius" config={config} onChange={onChange} step={0.5} /><p className="control-note">Up to {config.cornerRadius} mm radius. Tight corners use a smaller radius to preserve the profile.</p></>}
      </div>
    </ConfigSection>
    <ConfigSection number="04" title="Cable management" summary={config.cableHoles ? `${stand.cableHoles.totalCount} holes · Ø${Number(stand.cableHoles.diameter.toFixed(2))} mm` : "Off · Solid braces"}>
      <div className="inline-field"><label htmlFor="stand-cable-holes">Cable holes in braces</label><button id="stand-cable-holes" role="switch" aria-checked={config.cableHoles} aria-label="Cable holes in braces" aria-describedby="stand-cable-holes-note" className={`toggle ${config.cableHoles ? "toggle-on" : ""}`} onClick={() => onChange({ cableHoles: !config.cableHoles })}><span>{config.cableHoles ? <Plus size={10} /> : <Minus size={10} />}</span></button></div>
      <p className="control-note" id="stand-cable-holes-note">{config.advancedMode ? "Round openings in clear bays of both diagonal brace directions. Cables route between them; these are not straight-through passages." : "Round openings between the support ribs, aligned through all three braces to route cables front to back."}</p>
      {config.cableHoles && <><Dimension label="Cable hole diameter" field="cableHoleDiameter" config={config} onChange={onChange} /><p className="control-note" role="status">{config.advancedMode ? `${stand.cableHoles.totalCount} holes across both brace directions · Ø${Number(stand.cableHoles.diameter.toFixed(2))} mm. Openings are omitted where a bay is too short.` : `${stand.cableHoles.countPerBrace} × Ø${Number(stand.cableHoles.diameter.toFixed(2))} mm per brace · ${stand.cableHoles.totalCount} holes total.`}{stand.cableHoles.diameter < config.cableHoleDiameter ? " Diameter reduced to preserve material around the openings." : ""} At least {stand.cableHoles.minimumWeb} mm of acrylic remains to edges and joints. Size for your widest connector; cables thread through the closed holes.</p></>}
    </ConfigSection>
    <ConfigSection number="05" title="Your parts" summary={`${stand.ribCount} ribs + ${stand.braceCount} braces · ${stand.parts.length} parts`}>
      <div className="stand-parts">{config.advancedMode || object ? stand.parts.map(part => <div key={part.id}><strong>1×</strong><span>{part.label}<small>{part.width.toFixed(1)} × {part.height.toFixed(1)} mm</small></span></div>) : <><div><strong>{stand.ribCount}×</strong><span>Solid support ribs<small>{rib.width.toFixed(1)} × {rib.height.toFixed(1)} mm</small></span></div><div><strong>{stand.braceCount}×</strong><span>Slotted cross braces<small>{stand.braceWidth.toFixed(1)} × {stand.braceHeight.toFixed(1)} mm</small></span></div></>}</div>
      <p className="control-note">{config.advancedMode ? "The main sheets carry the synth in a crossed grid. Four lower braces, two in each direction, tie the grid together. Longer instruments add repeated main supports automatically." : `Ribs spaced ${stand.supportSpacing.toFixed(0)} mm apart. Auto adds ribs to keep spans at or below 220 mm.`} All {stand.parts.length} pieces use the same sheet thickness.</p>
      <div className="hardware-note"><span className="hardware-dot" />Acrylic only <span>Slot together · no glue</span></div>
      <p className="control-note">{config.advancedMode ? "Stand family B (main supports and braces) slots-up, then lower family A slots-down. Match each labelled part to the cutting layout. Main supports reaching the front carry integral stops." : "Stand the braces slots-up, then lower the ribs slots-down. Manual-dimension stands include front stops."} Remove the synth before moving the stand; the joints lift apart.</p>
      <p className="stand-prototype-note">Prototype design · no load rating. Support spacing is a layout rule, not a strength calculation. Test fit, flex, racking, surface grip and tipping before use.</p>
    </ConfigSection>
  </aside></div>;
}
