"""Extract the MYND port access wire at the flange face (0.03 mm chord tolerance).
Usage: /path/to/ocp-python scripts/extract-mynd-port.py /path/to/Port-housing.stp
Requires cadquery-ocp 8. Output: lib/mynd-port.ts. Source is CC-BY-SA-4.0.
"""
import sys, hashlib
from pathlib import Path
from OCP.STEPControl import STEPControl_Reader
from OCP.TopExp import TopExp_Explorer
from OCP.TopAbs import TopAbs_FACE,TopAbs_WIRE
from OCP.TopoDS import TopoDS
from OCP.BRepAdaptor import BRepAdaptor_Surface,BRepAdaptor_Curve
from OCP.GeomAbs import GeomAbs_Plane
from OCP.BRepTools import BRepTools_WireExplorer
from OCP.GCPnts import GCPnts_QuasiUniformDeflection
import json
source=Path(sys.argv[1]);r=STEPControl_Reader();r.ReadFile(str(source));r.TransferRoots();s=r.OneShape();ex=TopExp_Explorer(s,TopAbs_FACE)
rings=[]
while ex.More():
 face=TopoDS.Face(ex.Current());surf=BRepAdaptor_Surface(face)
 if surf.GetType()==GeomAbs_Plane and abs(surf.Plane().Axis().Direction().X())>.999 and abs(surf.Plane().Location().X()+114.5)<.001:
  w=TopExp_Explorer(face,TopAbs_WIRE)
  while w.More():
   wire=TopoDS.Wire(w.Current());edges=BRepTools_WireExplorer(wire);pts=[]
   while edges.More():
    edge=TopoDS.Edge(edges.Current());curve=BRepAdaptor_Curve(edge);sampler=GCPnts_QuasiUniformDeflection(curve,.03);p=[[sampler.Value(i).Y(),sampler.Value(i).Z()] for i in range(1,sampler.NbPoints()+1)]
    if pts and sum((a-b)**2 for a,b in zip(pts[-1],p[-1]))<sum((a-b)**2 for a,b in zip(pts[-1],p[0])):p=p[::-1]
    pts.extend(p);edges.Next()
   rings.append(pts);w.Next()
 ex.Next()

# The central access wire spans ~41 mm; the outside flange spans 56 mm.
profile=next(p for p in rings if 40 < max(x[0] for x in p)-min(x[0] for x in p) < 42)
points=[]
for y,z in profile:
 point=[round(y-55.86,5),round(z-51.28,5)]
 if not points or point!=points[-1]:points.append(point)
if points[-1]!=points[0]:points.append(points[0])
area=sum(a[0]*b[1]-b[0]*a[1] for a,b in zip(points,points[1:]))
if area<0:points.reverse()
width=round(max(p[0] for p in points)-min(p[0] for p in points),5)
height=round(max(p[1] for p in points)-min(p[1] for p in points),5)
text="// Teufel MYND port housing, CC-BY-SA-4.0. Generated by scripts/extract-mynd-port.py.\n"
text+="// Source STEP SHA256: "+hashlib.sha256(source.read_bytes()).hexdigest()+"\n"
text+="// Access wire at source X=-114.5; 0.03 mm chord tolerance.\n"
text+="export const myndPort = { sourceFace: -114.5, depthOrigin: 55.86, height: 51.28, width: "+str(width)+", openingHeight: "+str(height)+" };\n"
text+="export const myndPortOpening: [number, number][] = "+json.dumps(points,separators=(",", ":"))+";\n"
text+="""// Source Y/Z centres; side bores Ø2.6, recessed top/bottom bores Ø3.5.
// New M2.5 / M3 through fasteners, clearance holes and clamp lengths are proposed.
export const myndPortMounts = [
  { y: 31.36, z: 51.28, diameter: 2.8, shaftRadius: 1.25, clampDepth: 2, seatDepth: 0 },
  { y: 80.86, z: 51.28, diameter: 2.8, shaftRadius: 1.25, clampDepth: 2, seatDepth: 0 },
  { y: 54.36, z: 37.03, diameter: 3.4, shaftRadius: 1.5, clampDepth: 9, seatDepth: 7 },
  { y: 54.36, z: 66.03, diameter: 3.4, shaftRadius: 1.5, clampDepth: 9, seatDepth: 7 },
];
"""
Path("lib/mynd-port.ts").write_text(text)
print(f"Extracted {len(points)} access-wire points: {width} × {height} mm")
